import type{AiMessageInput,StorySaveProjection}from'./story-domain.ts'
import type{Rpc}from'./rpc-shape.ts'
import{unwrap}from'./rpc-shape.ts'

type StoryHistoryPage={events:Array<{event:any}>;hasMore?:boolean}
export interface StoryApi{sessions:{create(payload:Record<string,unknown>):Promise<Rpc<{sessionId:string}>>;fork(payload:Record<string,unknown>):Promise<Rpc<{sessionId:string}>>;history(payload:Record<string,unknown>):Promise<Rpc<StoryHistoryPage>>;prompt(payload:Record<string,unknown>):Promise<Rpc<{accepted:true}>>;cancel(payload:Record<string,unknown>):Promise<Rpc<{accepted:true}>>};workspace:{archiveSession(payload:Record<string,unknown>):Promise<Rpc<unknown>>}}
export interface AiBridgeResult{messages:AiMessageInput[];raw:string;turnId?:string;dshTurn?:number}
export interface RecoveredAiBridgeResult{channelId:string;result:AiBridgeResult;turnId:string}
export interface AiDispatchEvidence{turnId:string;sessionId:string;baseline:number;dshRequestId?:string}
export interface AiRecoveryEvidence{turnId:string;sessionId:string;channelId:string;dshRequestId:string;dshTurn?:number}
export interface AiDispatchHooks{turnId?:string;transactionId?:string;beforeDispatch?(evidence:AiDispatchEvidence):Promise<void>;afterAccepted?(evidence:AiDispatchEvidence):Promise<void>;afterUncertain?(evidence:AiDispatchEvidence,error:unknown):Promise<void>}
export type AiTurnState='queued'|'running'|'waiting-choice'|'uncertain'|'completed'|'failed'|'cancelled'
export interface AiTurnPreview{turnId:string;channelId:string;messages:AiMessageInput[]}
export interface AiTurn{version:1;id:string;sessionId:string;baseline:number;channelId:string;prompt:string;state:AiTurnState;dshRequestId?:string;dshTurn?:number;result?:AiBridgeResult;error?:string;preview?:AiTurnPreview}
export interface OrphanedSessionDiagnostic{saveId:string;packId?:string;sessionId:string;removedAt:string;reason:'save-deleted';lastTurnState?:AiTurnState}
type StoredTurn=AiTurn

function eventTurn(event:any):number|undefined{const value=Number(event?.data?.turn);return Number.isSafeInteger(value)&&value>=0?value:undefined}
function eventSeq(event:any):number|undefined{const value=Number(event?.seq);return Number.isSafeInteger(value)&&value>=0?value:undefined}
function nativeTurnForRequest(events:Array<{event:any}>,afterSeq:number,requestId:string):number|undefined{const ordered=events.map(entry=>entry.event).filter(event=>eventSeq(event)!==undefined&&Number(event.seq)>afterSeq).sort((left,right)=>Number(left.seq)-Number(right.seq));const turns=new Set<number>();let activeTurn:number|undefined;for(const event of ordered){if(event?.type==='turn/start'){activeTurn=eventTurn(event);continue}if(event?.type!=='user/message')continue;const source=event?.data?.source;if(source?.kind!=='user'||source.rpcId!==requestId)continue;if(activeTurn!==undefined)turns.add(activeTurn)}if(turns.size>1)throw new Error(`DSH request correlation 匹配多个 native turn：${requestId}`);return turns.values().next().value}
function hasNativeTurnStart(events:Array<{event:any}>,afterSeq:number,dshTurn:number):boolean{return events.some(entry=>entry.event?.type==='turn/start'&&Number(entry.event.seq)>afterSeq&&eventTurn(entry.event)===dshTurn)}
function assistantText(events:Array<{event:any}>,afterSeq:number,dshTurn?:number):string|undefined{const messages=events.map(x=>x.event).filter(e=>e?.type==='assistant/message'&&Number(e.seq)>afterSeq&&(dshTurn===undefined||eventTurn(e)===dshTurn));const data=messages.at(-1)?.data;const blocks=data?.message?.content??data?.content;if(!Array.isArray(blocks))return undefined;return blocks.filter((b:any)=>b?.type==='text'&&typeof b.text==='string').map((b:any)=>b.text).join('\n').trim()||undefined}
function turnEnded(events:Array<{event:any}>,afterSeq:number,dshTurn?:number):boolean{return events.some(x=>{const event=x.event;return event?.type==='turn/end'&&Number(event.seq)>afterSeq&&(dshTurn===undefined||eventTurn(event)===dshTurn)})}
function responseRpcId(value:Rpc<unknown>):string|undefined{const raw=value.rpcId;return typeof raw==='string'&&raw.trim()!==''?raw:undefined}
function parseMessages(raw:string,projection:StorySaveProjection,channelId:string):AiMessageInput[]{const fenced=raw.match(/```(?:json)?\s*([\s\S]*?)```/u)?.[1]??raw;const parse=(text:string):AiMessageInput[]=>{const value=JSON.parse(text)as{messages?:unknown};if(!Array.isArray(value.messages))throw new Error('AI 输出缺少 messages 数组');const id=(role:string):string=>role==='narration'||role==='narrator'?projection.participants.find(p=>p.role==='narrator')?.id??role:role==='system'?projection.participants.find(p=>p.role==='system')?.id??role:role;return value.messages.map((item:any)=>({senderId:id(String(item.senderId)),kind:String(item.kind)as AiMessageInput['kind'],content:String(item.content)}))};const repair=(text:string):string=>{let out='';let open=false;const cjk=(c:string|undefined)=>c!==undefined&&/[\u4e00-\u9fff\u3000-\u303f\uff00-\uffef]/.test(c);for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='\\'&&open){out+=ch+(text[i+1]??'');i++;continue}if(ch!=='"'){out+=ch;continue}if(!open){open=true;out+=ch;continue}const prev=text[i-1],next=text[i+1];if((cjk(prev)&&(cjk(next)||next==='"'))||(cjk(prev)&&next===undefined))out+='\\"';else{open=false;out+=ch}}return out};try{return parse(fenced)}catch{const fixed=repair(fenced);if(fixed!==fenced){try{return parse(fixed)}catch{/* remain structured error */}}throw new Error('AI 返回了无法解析的结构化消息；未写入剧情，请重试')}}

export class StoryAiBridge{
 constructor(private readonly api:StoryApi,private readonly storage:Pick<Storage,'getItem'|'setItem'>,private readonly delay:(ms:number)=>Promise<void>=(ms)=>new Promise(resolve=>setTimeout(resolve,ms)),private readonly cloneRuntime:(payload:{packId:string;sourceSessionId:string;targetSessionId:string})=>Promise<void>=async(payload)=>{const response=await fetch('/story-engine/api/runtime/clone',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});if(!response.ok){const detail=await response.json().catch(()=>({}))as{error?:string};throw new Error(detail.error??`复制剧情状态失败：${response.status}`)}}){}
 private cached=new Map<string,string>()
 private previews=new Map<string,AiTurnPreview>()
 private key(saveId:string):string{return`dsh-story-ai-session:${saveId}`}
 private pendingKey(saveId:string):string{return`dsh-story-ai-pending:${saveId}`}
 private orphanKey(saveId:string):string{return`dsh-story-ai-orphan:${saveId}`}
 private remember(saveId:string,sessionId:string):void{this.storage.setItem(this.key(saveId),sessionId);this.cached.set(saveId,sessionId)}
 private readTurn(saveId:string):StoredTurn|null{const raw=this.storage.getItem(this.pendingKey(saveId));if(!raw)return null;try{const value=JSON.parse(raw)as Partial<StoredTurn>;if(value.version===undefined&&typeof value.sessionId==='string'&&typeof value.baseline==='number'&&Number.isFinite(value.baseline)&&typeof value.channelId==='string'){const migrated:StoredTurn={version:1,id:`legacy-${value.sessionId}-${value.baseline}`,sessionId:value.sessionId,baseline:value.baseline,channelId:value.channelId,prompt:'',state:'running'};this.writeTurn(saveId,migrated);return migrated}if(value.version!==1||typeof value.id!=='string'||typeof value.sessionId!=='string'||!Number.isFinite(value.baseline)||typeof value.channelId!=='string'||typeof value.prompt!=='string'||typeof value.state!=='string'||(value.dshRequestId!==undefined&&typeof value.dshRequestId!=='string')||(value.dshTurn!==undefined&&(!Number.isSafeInteger(value.dshTurn)||value.dshTurn<0))||!['queued','running','waiting-choice','uncertain','completed','failed','cancelled'].includes(value.state))return null;return value as StoredTurn}catch{return null}}
 private writeTurn(saveId:string,turn:StoredTurn):void{this.storage.setItem(this.pendingKey(saveId),JSON.stringify(turn))}
 private change(saveId:string,turn:StoredTurn,change:Partial<StoredTurn>):StoredTurn{const next={...turn,...change};if(next.state==='failed'||next.state==='cancelled')this.previews.delete(saveId);this.writeTurn(saveId,next);return next}
 private refresh(saveId:string,turn:StoredTurn):StoredTurn{const stored=this.readTurn(saveId);return stored?.id===turn.id?stored:turn}
 private ensureNotCancelled(saveId:string,turn:StoredTurn):StoredTurn{const latest=this.refresh(saveId,turn);if(latest.state==='cancelled')throw new Error('AI 回合已取消');return latest}
 turn(saveId:string):AiTurn|null{const turn=this.readTurn(saveId);if(turn===null)return null;const preview=this.previews.get(saveId);return preview?.turnId===turn.id?{...turn,preview}:turn}
 acknowledge(saveId:string,turnId:string):void{const turn=this.readTurn(saveId);if(turn?.id===turnId&&['completed','failed','cancelled'].includes(turn.state)){this.storage.setItem(this.pendingKey(saveId),'');this.previews.delete(saveId)}}
 private async session(saveId:string,agentPreset:string):Promise<string>{let id=this.currentSessionId(saveId);if(id===null){id=crypto.randomUUID();this.remember(saveId,id)}const created=unwrap(await this.api.sessions.create({sessionId:id,cwd:'D:/DSH-Story-Engine',agentPreset}),'创建文字游戏会话');await this.api.workspace.archiveSession({sessionId:created.sessionId});return created.sessionId}
 currentSessionId(saveId:string):string|null{const cached=this.cached.get(saveId);if(cached!==undefined)return cached;const persisted=this.storage.getItem(this.key(saveId));if(persisted===null||persisted.trim()==='')return null;this.cached.set(saveId,persisted);return persisted}
 async forkSave(sourceSaveId:string,targetSaveId:string,packId:string):Promise<string|null>{const sourceSessionId=this.currentSessionId(sourceSaveId);if(sourceSessionId===null)return null;const forked=unwrap(await this.api.sessions.fork({sessionId:sourceSessionId,increaseTitle:false}),'复制文字游戏会话');await this.api.workspace.archiveSession({sessionId:forked.sessionId});await this.cloneRuntime({packId,sourceSessionId,targetSessionId:forked.sessionId});this.remember(targetSaveId,forked.sessionId);return forked.sessionId}
 /** DSH exposes archive/cancel but no safe session-delete RPC; retain a local diagnostic rather than guessing. */
 async releaseSave(saveId:string,packId?:string):Promise<OrphanedSessionDiagnostic|undefined>{const sessionId=this.currentSessionId(saveId);const turn=this.readTurn(saveId);if(turn!==null&&['queued','running','waiting-choice','uncertain'].includes(turn.state))throw new Error('删除前必须先取消仍在运行或结果不确定的 AI 回合');if(sessionId===null)return undefined;const diagnostic:OrphanedSessionDiagnostic={saveId,...(packId===undefined?{}:{packId}),sessionId,removedAt:new Date().toISOString(),reason:'save-deleted',...(turn===null?{}:{lastTurnState:turn.state})};this.storage.setItem(this.orphanKey(saveId),JSON.stringify(diagnostic));this.storage.setItem(this.key(saveId),'');this.storage.setItem(this.pendingKey(saveId),'');this.cached.delete(saveId);this.previews.delete(saveId);return diagnostic}
 async cancel(saveId:string):Promise<void>{const turn=this.readTurn(saveId);if(turn===null||!['queued','running','waiting-choice','uncertain'].includes(turn.state))return;try{unwrap(await this.api.sessions.cancel({sessionId:turn.sessionId}),'取消 AI 回合');this.previews.delete(saveId);this.change(saveId,turn,{state:'cancelled',error:undefined})}catch(error){this.change(saveId,turn,{state:'uncertain',error:`取消结果不确定：${error instanceof Error?error.message:String(error)}`});throw error}}
 markWaitingChoice(saveId:string,sessionId:string):void{const turn=this.readTurn(saveId);if(turn!==null&&turn.sessionId===sessionId&&['queued','running','uncertain'].includes(turn.state))this.change(saveId,turn,{state:'waiting-choice'})}
 private async correlatedHistory(turn:StoredTurn,tail:StoryHistoryPage):Promise<{events:Array<{event:any}>;dshTurn?:number}>{const requestId=turn.dshRequestId;if(requestId===undefined)return{events:tail.events,...(turn.dshTurn===undefined?{}:{dshTurn:turn.dshTurn})};let page=tail;let events=[...tail.events];let dshTurn=turn.dshTurn??nativeTurnForRequest(events,turn.baseline,requestId);for(let pages=0;pages<64;pages+=1){if(dshTurn!==undefined&&hasNativeTurnStart(events,turn.baseline,dshTurn))return{events,dshTurn};const seqs=page.events.map(entry=>eventSeq(entry.event)).filter((seq):seq is number=>seq!==undefined);const first=seqs.length===0?undefined:Math.min(...seqs);if(first===undefined||first<=turn.baseline+1||page.hasMore!==true)return{events,...(dshTurn===undefined?{}:{dshTurn})};page=unwrap(await this.api.sessions.history({sessionId:turn.sessionId,beforeSeq:first,maxMessages:20}),'读取回复关联历史');events=[...page.events,...events];if(dshTurn===undefined)dshTurn=nativeTurnForRequest(events,turn.baseline,requestId)}throw new Error(`DSH request correlation 历史回溯超过安全页数：${requestId}`)}
 private async wait(projection:StorySaveProjection,initial:StoredTurn):Promise<RecoveredAiBridgeResult>{let turn=initial;for(let attempt=0;attempt<3600;attempt+=1){turn=this.ensureNotCancelled(projection.saveId,turn);await this.delay(500);turn=this.ensureNotCancelled(projection.saveId,turn);try{const history=unwrap(await this.api.sessions.history({sessionId:turn.sessionId,maxMessages:20}),'读取回复');turn=this.ensureNotCancelled(projection.saveId,turn);const correlated=await this.correlatedHistory(turn,history);let dshTurn=correlated.dshTurn;if(dshTurn!==undefined&&turn.dshTurn===undefined)turn=this.change(projection.saveId,turn,{dshTurn});else if(dshTurn===undefined)dshTurn=turn.dshTurn;const correlationPending=turn.dshRequestId!==undefined&&dshTurn===undefined;const raw=correlationPending?undefined:assistantText(correlated.events,turn.baseline,dshTurn);const ended=correlationPending?false:turnEnded(correlated.events,turn.baseline,dshTurn);if(raw!==undefined&&ended){let result:AiBridgeResult;try{result={raw,messages:parseMessages(raw,projection,turn.channelId),...(dshTurn===undefined?{}:{dshTurn})}}catch(error){this.change(projection.saveId,turn,{state:'failed',error:error instanceof Error?error.message:String(error)});throw error}turn=this.change(projection.saveId,turn,{state:'completed',result,error:undefined});return{channelId:turn.channelId,result,turnId:turn.id}}if(raw!==undefined){try{this.previews.set(projection.saveId,{turnId:turn.id,channelId:turn.channelId,messages:parseMessages(raw,projection,turn.channelId)})}catch{/* incomplete JSON stays invisible until it becomes verifiable */}}if(raw===undefined&&ended){const error='AI 回合已结束，但没有产生结构化回复';this.change(projection.saveId,turn,{state:'failed',error});throw new Error(error)}if(turn.state==='queued')turn=this.change(projection.saveId,turn,{state:'running'})}catch(error){turn=this.refresh(projection.saveId,turn);if(turn.state==='cancelled')throw new Error('AI 回合已取消');if(error instanceof Error&&(error.message==='AI 回合已结束，但没有产生结构化消息'||error.message==='AI 回合已结束，但没有产生结构化回复'||error.message.includes('无法解析的结构化消息')))throw error;this.change(projection.saveId,turn,{state:'uncertain',error:`读取 AI 回合结果不确定：${error instanceof Error?error.message:String(error)}`});throw error}}const error='AI 回合仍在运行；下次打开存档会继续从 history 恢复';this.change(projection.saveId,turn,{state:'uncertain',error});throw new Error(error)}
 async recover(projection:StorySaveProjection):Promise<RecoveredAiBridgeResult|null>{const turn=this.readTurn(projection.saveId);if(turn===null)return null;const sessionId=this.currentSessionId(projection.saveId);if(sessionId===null||sessionId!==turn.sessionId||!projection.channels.some(channel=>channel.id===turn.channelId)){this.change(projection.saveId,turn,{state:'failed',error:'待恢复的 AI 回合与当前存档不匹配'});throw new Error('待恢复的 AI 回合与当前存档不匹配')}if(turn.state==='completed'){if(turn.result===undefined)throw new Error('已完成回合缺少可验证结果');return{channelId:turn.channelId,result:turn.result,turnId:turn.id}}if(turn.state==='cancelled'||turn.state==='failed')return null;return this.wait(projection,turn)}
 async recoverFromEvidence(projection:StorySaveProjection,evidence:AiRecoveryEvidence):Promise<RecoveredAiBridgeResult>{if(!projection.channels.some(channel=>channel.id===evidence.channelId))throw new Error(`journal recovery channel 不存在：${evidence.channelId}`);const currentSession=this.currentSessionId(projection.saveId);if(currentSession!==null&&currentSession!==evidence.sessionId)throw new Error(`journal recovery session 冲突：${currentSession} != ${evidence.sessionId}`);if(currentSession===null)this.remember(projection.saveId,evidence.sessionId);const existing=this.readTurn(projection.saveId);if(existing!==null){if(existing.id!==evidence.turnId||existing.sessionId!==evidence.sessionId||existing.channelId!==evidence.channelId)throw new Error('本地 pending turn 与 journal recovery identity 冲突');if(existing.dshRequestId!==undefined&&existing.dshRequestId!==evidence.dshRequestId)throw new Error('本地 pending turn 与 journal DSH request identity 冲突');const merged=existing.dshRequestId===undefined||existing.dshTurn===undefined&&evidence.dshTurn!==undefined?this.change(projection.saveId,existing,{dshRequestId:evidence.dshRequestId,...(existing.dshTurn===undefined&&evidence.dshTurn!==undefined?{dshTurn:evidence.dshTurn}:{})}):existing;const recovered=merged.state==='completed'?(merged.result===undefined?null:{channelId:merged.channelId,result:merged.result,turnId:merged.id}):await this.recover(projection);if(recovered===null)throw new Error(`journal hidden turn ${evidence.turnId} 无法从本地状态恢复`);return recovered}const rebuilt:StoredTurn={version:1,id:evidence.turnId,sessionId:evidence.sessionId,baseline:-1,channelId:evidence.channelId,prompt:'journal-recovery',state:'uncertain',dshRequestId:evidence.dshRequestId,...(evidence.dshTurn===undefined?{}:{dshTurn:evidence.dshTurn})};this.writeTurn(projection.saveId,rebuilt);return this.wait(projection,rebuilt)}
 private transactionInstruction(transactionId?:string):string{return transactionId===undefined?'':`当前 player transaction_id：${transactionId}。本回合所有会修改 canonical runtime state 的 story_* 调用必须携带完全相同的 transaction_id；同一原子写操作重试必须复用原 operation_id。\n`}
 private promptFor(projection:StorySaveProjection,channelId:string,playerInput:string,transactionId?:string):string{const channel=projection.channels.find(c=>c.id===channelId);if(channel===undefined)throw new Error('频道不存在');return`当前文字游戏频道：${channel.title}\n当前进度：${projection.frame.seasonLabel} ${projection.frame.episodeLabel} ${projection.frame.sceneLabel}\n玩家输入：${playerInput}\n${this.transactionInstruction(transactionId)}可用发送者：${channel.participantIds.join(', ')}，旁白和系统也可使用。请推进剧情并调用必要的 story_* 工具。最终仅输出 JSON：{"messages":[{"senderId":"人物ID","kind":"dialogue|narration|action|system|work-dispatch|relationship|episode-summary","content":"内容"}]}。不得替玩家角色发言或决定。注意：content 内的对白引用请使用中文引号“”或「」，不要使用英文双引号 "，以免破坏 JSON 格式。`}
 private retryPrompt(projection:StorySaveProjection,channelId:string,transactionId?:string):string{const channel=projection.channels.find(c=>c.id===channelId);if(channel===undefined)throw new Error('频道不存在');return`继续刚才未完成的文字游戏回合。不要再次转述或提交玩家输入、选择或已提交的剧情消息。当前频道：${channel.title}；当前进度：${projection.frame.seasonLabel} ${projection.frame.episodeLabel} ${projection.frame.sceneLabel}。\n${this.transactionInstruction(transactionId)}只在通过必要的 story_* 工具后输出新的结构化 JSON 回复。`}
 private continuationPrompt(projection:StorySaveProjection,channelId:string,instruction:string,transactionId?:string):string{const channel=projection.channels.find(c=>c.id===channelId);if(channel===undefined)throw new Error('频道不存在');if(instruction.trim()==='')throw new Error('transaction continuation 指令不能为空');return`继续同一 player transaction 的恢复回合。不要再次转述或提交原玩家输入，也不要重复已经由 Core receipt 确认 applied/replayed 的 canonical mutation。当前频道：${channel.title}；当前进度：${projection.frame.seasonLabel} ${projection.frame.episodeLabel} ${projection.frame.sceneLabel}。\n${this.transactionInstruction(transactionId)}恢复要求：${instruction}\n需要重试的同一原子 mutation 必须复用原 operation_id。完成必要修复后，仅输出这一轮新的结构化 JSON 回复。`}
 private async start(projection:StorySaveProjection,channelId:string,prompt:string,hooks:AiDispatchHooks={}):Promise<RecoveredAiBridgeResult>{const sessionId=await this.session(projection.saveId,projection.agentPreset??`story-${projection.packId}`);const before=unwrap(await this.api.sessions.history({sessionId,maxMessages:20}),'读取会话');const baseline=Math.max(-1,...before.events.map(x=>Number(x.event?.seq??-1)));const evidence:AiDispatchEvidence={turnId:hooks.turnId??crypto.randomUUID(),sessionId,baseline};await hooks.beforeDispatch?.(evidence);let turn:StoredTurn={version:1,id:evidence.turnId,sessionId,baseline,channelId,prompt,state:'queued'};this.previews.delete(projection.saveId);this.writeTurn(projection.saveId,turn);let acceptedEvidence=evidence;try{const response=await this.api.sessions.prompt({sessionId,mode:'queue',content:[{type:'text',text:prompt}],clientTimeZone:Intl.DateTimeFormat().resolvedOptions().timeZone});unwrap(response,'发送');const dshRequestId=responseRpcId(response);if(dshRequestId!==undefined)acceptedEvidence={...evidence,dshRequestId}}catch(error){const latest=this.readTurn(projection.saveId);if(latest?.id===turn.id&&!['completed','cancelled','failed'].includes(latest.state))turn=this.change(projection.saveId,latest,{state:'uncertain',error:`发送结果不确定：${error instanceof Error?error.message:String(error)}`});await hooks.afterUncertain?.(evidence,error);throw error}turn=this.change(projection.saveId,turn,{state:'running',error:undefined,...(acceptedEvidence.dshRequestId===undefined?{}:{dshRequestId:acceptedEvidence.dshRequestId})});try{await hooks.afterAccepted?.(acceptedEvidence)}catch(error){const latest=this.readTurn(projection.saveId);if(latest?.id===turn.id&&!['completed','cancelled','failed'].includes(latest.state))turn=this.change(projection.saveId,latest,{state:'uncertain',error:`AI 回合已接受，但事务记录结果不确定：${error instanceof Error?error.message:String(error)}`});await hooks.afterUncertain?.(acceptedEvidence,error);throw error}return this.wait(projection,turn)}
 async send(projection:StorySaveProjection,channelId:string,playerInput:string,hooks:AiDispatchHooks={}):Promise<AiBridgeResult>{const prior=this.readTurn(projection.saveId);if(prior!==null&&['queued','running','waiting-choice','uncertain','completed'].includes(prior.state))throw new Error('当前存档已有待处理 AI 回合；请等待、恢复或取消后再发送');const completed=await this.start(projection,channelId,this.promptFor(projection,channelId,playerInput,hooks.transactionId),hooks);return{...completed.result,turnId:completed.turnId}}
 async retry(projection:StorySaveProjection,hooks:AiDispatchHooks={}):Promise<AiBridgeResult>{const prior=this.readTurn(projection.saveId);if(prior===null||!['failed','cancelled'].includes(prior.state)||prior.prompt==='')throw new Error('当前 AI 回合不可安全重试');const completed=await this.start(projection,prior.channelId,this.retryPrompt(projection,prior.channelId,hooks.transactionId),hooks);return{...completed.result,turnId:completed.turnId}}
 async continueTransaction(projection:StorySaveProjection,channelId:string,instruction:string,hooks:AiDispatchHooks={}):Promise<AiBridgeResult>{const prior=this.readTurn(projection.saveId);if(prior!==null&&!['completed','failed','cancelled'].includes(prior.state))throw new Error(`当前 AI 回合状态为 ${prior.state}，不能启动 transaction continuation`);if(prior===null&&this.currentSessionId(projection.saveId)===null)throw new Error('transaction continuation 缺少可恢复 hidden session');const completed=await this.start(projection,channelId,this.continuationPrompt(projection,channelId,instruction,hooks.transactionId),hooks);return{...completed.result,turnId:completed.turnId}}
}
