import{assertSaveId,assertTransactionId,createPreparedTransaction,validateTransactionRecord,type StoryTransactionRecord}from'../transaction-journal.ts'

const TERMINAL=new Set(['committed','cancelled','failed'])
export class HostTransactionJournal{
 private readonly tails=new Map<string,Promise<void>>()
 constructor(private readonly fetcher:typeof fetch=(input,init)=>fetch(input,init)){}
 private key(saveId:string,transactionId:string):string{return`${saveId}:${transactionId}`}
 private base(saveId:string):string{assertSaveId(saveId);return`/story-engine/api/transactions/${encodeURIComponent(saveId)}`}
 private endpoint(saveId:string,transactionId:string):string{assertTransactionId(transactionId);return`${this.base(saveId)}/${encodeURIComponent(transactionId)}`}
 private identity(record:StoryTransactionRecord,saveId:string,transactionId?:string):StoryTransactionRecord{if(record.saveId!==saveId||(transactionId!==undefined&&record.transactionId!==transactionId))throw new Error('transaction journal 响应身份不匹配');return record}
 private serial<T>(saveId:string,transactionId:string,work:()=>Promise<T>):Promise<T>{const key=this.key(saveId,transactionId);const previous=this.tails.get(key)??Promise.resolve();let release!:()=>void;const gate=new Promise<void>(resolve=>{release=resolve});const queued=previous.then(()=>gate);this.tails.set(key,queued);const task=previous.then(work);return task.finally(()=>{release();if(this.tails.get(key)===queued)this.tails.delete(key)})}
 async list(saveId:string):Promise<StoryTransactionRecord[]>{const response=await this.fetcher(this.base(saveId),{headers:{accept:'application/json'}});if(!response.ok)throw new Error(`读取 transaction journal 失败：${response.status}`);const body=await response.json()as{transactions?:unknown};if(!Array.isArray(body.transactions))throw new Error('transaction journal 列表格式无效');const seen=new Set<string>();return body.transactions.map(value=>{const record=this.identity(validateTransactionRecord(value),saveId);if(seen.has(record.transactionId))throw new Error(`transaction journal 列表包含重复 transactionId：${record.transactionId}`);seen.add(record.transactionId);return record})}
 async listOpen(saveId:string):Promise<StoryTransactionRecord[]>{return(await this.list(saveId)).filter(record=>!TERMINAL.has(record.status))}
 async load(saveId:string,transactionId:string):Promise<StoryTransactionRecord|undefined>{const response=await this.fetcher(this.endpoint(saveId,transactionId),{headers:{accept:'application/json'}});if(response.status===204||response.status===404)return undefined;if(!response.ok)throw new Error(`读取 transaction 失败：${response.status}`);return this.identity(validateTransactionRecord(await response.json()),saveId,transactionId)}
 async save(record:StoryTransactionRecord,bootstrap=false):Promise<StoryTransactionRecord>{const submitted=validateTransactionRecord(record);return this.serial(submitted.saveId,submitted.transactionId,async()=>{const response=await this.fetcher(this.endpoint(submitted.saveId,submitted.transactionId),{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({expectedRevision:bootstrap?-1:submitted.revision-1,transaction:submitted})});if(response.status===409){const detail=await response.json().catch(()=>({}))as{error?:string};throw new Error(detail.error??'transaction journal 发生幂等或版本冲突，请重新读取后恢复')};if(!response.ok){const detail=await response.json().catch(()=>({}))as{error?:string};throw new Error(detail.error??`保存 transaction 失败：${response.status}`)}const saved=this.identity(validateTransactionRecord(await response.json()),submitted.saveId,submitted.transactionId);if(JSON.stringify(saved)!==JSON.stringify(submitted))throw new Error('transaction journal 保存响应与提交内容不匹配');return saved})}
 async prepare(input:{transactionId?:string;saveId:string;channelId:string;text:string;baseProjectionRevision:number;now?:Date}):Promise<StoryTransactionRecord>{const record=await createPreparedTransaction(input);return this.save(record,true)}
}
