import{reviseTransaction,type StoryHiddenTurnKind,type StoryHiddenTurnRef,type StoryTransactionRecord}from'../transaction-journal.ts'
import type{HostTransactionJournal}from'./host-transactions.ts'
import type{HostProjectionStorage}from'./host-persistence.ts'
import type{AiBridgeResult,AiDispatchEvidence,AiDispatchHooks,AiTurn,RecoveredAiBridgeResult,StoryAiBridge}from'./ai-bridge.ts'
import type{CoreTransactionReconciler,CoreTransactionReconciliation}from'./core-reconciliation.ts'
import{appendPlayerMessage,type StorySaveProjection}from'./story-domain.ts'

type JournalPort=Pick<HostTransactionJournal,'listOpen'|'prepare'|'save'>
type ProjectionPort=Pick<HostProjectionStorage,'save'>
type AiPort=Pick<StoryAiBridge,'send'|'recover'|'recoverFromEvidence'|'retry'|'cancel'|'acknowledge'|'turn'>
type CorePort=Pick<CoreTransactionReconciler,'reconcile'>

const SOCIAL_ONLY_CORE:CorePort={async reconcile(record){if(record.operationRefs.length!==0)throw new Error(`transaction ${record.transactionId} 含 core operation，但 Core reconciler 未配置`);return{operations:[],hasCanonicalEffect:false,readyForSocialCommit:true,deterministicNoEffectFailure:false,unresolved:false}}}

type MutableTransaction={record:StoryTransactionRecord}
function detail(error:unknown):string{return error instanceof Error?error.message:String(error)}
function hiddenTerminal(state:StoryHiddenTurnRef['state']):boolean{return state==='completed'||state==='failed'||state==='cancelled'}

/** Browser coordinator for hidden, core-reconciliation, and social commit ordering. */
export class PlayerTransactionCoordinator{
 constructor(private readonly journal:JournalPort,private readonly projections:ProjectionPort,private readonly ai:AiPort,private readonly core:CorePort=SOCIAL_ONLY_CORE){}

 private async open(saveId:string):Promise<StoryTransactionRecord|undefined>{const records=await this.journal.listOpen(saveId);if(records.length>1)throw new Error(`存档存在多个未完成 transaction，必须先恢复：${records.map(record=>record.transactionId).join(', ')}`);return records[0]}
 private findHidden(record:StoryTransactionRecord,turnId:string):{index:number;turn:StoryHiddenTurnRef}{const index=record.hiddenTurns.findIndex(turn=>turn.turnId===turnId);if(index<0)throw new Error(`transaction 未记录 hidden turn：${turnId}`);return{index,turn:record.hiddenTurns[index]!}}
 private replaceHidden(record:StoryTransactionRecord,index:number,turn:StoryHiddenTurnRef):StoryHiddenTurnRef[]{return record.hiddenTurns.map((entry,current)=>current===index?turn:entry)}
 private async save(state:MutableTransaction,patch:Parameters<typeof reviseTransaction>[1]):Promise<void>{state.record=await this.journal.save(reviseTransaction(state.record,patch))}
 private persistedCanonical(record:StoryTransactionRecord,projection:StorySaveProjection):string|undefined{const turnId=record.canonicalResultTurnId;if(turnId===undefined)return undefined;const{turn}=this.findHidden(record,turnId);if(turn.state!=='completed')throw new Error(`canonical hidden turn 尚未完成：${turnId}`);return projection.messages.some(message=>message.turnId===turnId&&message.canonStatus==='committed')?turnId:undefined}
 private playerInputMatches(record:StoryTransactionRecord,projection:StorySaveProjection):boolean{const raw=record.input.text;const kind=raw.startsWith('(系统)')?'system':raw.startsWith('(行动)')?'action':'dialogue';const content=raw.replace(/^\((系统|行动)\)\s*/u,'');const player=projection.participants.find(p=>p.role==='player');const senderId=kind==='system'?(projection.participants.find(p=>p.role==='system')?.id??player?.id):player?.id;const last=projection.messages.at(-1);return senderId!==undefined&&last!==undefined&&last.channelId===record.input.channelId&&last.senderId===senderId&&last.kind===kind&&last.content===content&&last.turnId===`turn-${record.baseProjectionRevision+1}`&&last.canonStatus===(kind==='system'?'proposed':'committed')}
 private async ensurePlayerProjection(record:StoryTransactionRecord,projection:StorySaveProjection):Promise<StorySaveProjection>{if(projection.revision===record.baseProjectionRevision){const restored=appendPlayerMessage(projection,record.input.channelId,record.input.text);await this.projections.save(restored);return restored}if(projection.revision===record.baseProjectionRevision+1&&this.playerInputMatches(record,projection)){await this.projections.save(projection);return projection}throw new Error(`transaction ${record.transactionId} 的玩家 projection 无法安全恢复：revision ${projection.revision}, base ${record.baseProjectionRevision}`)}

 private async recoverBeforeHiddenDispatch(state:MutableTransaction,error:unknown,code='pre-hidden-dispatch-failed'):Promise<void>{if(state.record.status==='committed'||state.record.status==='cancelled'||state.record.status==='failed'||state.record.hiddenTurns.length!==0)return;const diagnostic={code,message:detail(error)};if(state.record.status==='needs-recovery'&&state.record.diagnostic?.code===diagnostic.code&&state.record.diagnostic.message===diagnostic.message)return;try{await this.save(state,{status:'needs-recovery',diagnostic})}catch{/* Preserve the original failure; the durable prepared/needs-recovery intent remains safe to inspect. */}}
 private async needsRecovery(state:MutableTransaction,turnId:string,error:unknown,code='hidden-dispatch-uncertain',evidence?:AiDispatchEvidence):Promise<void>{if(state.record.status==='committed'||state.record.status==='cancelled'||state.record.status==='failed')return;let hiddenTurns=state.record.hiddenTurns;const found=hiddenTurns.findIndex(turn=>turn.turnId===turnId);if(found>=0){const current=hiddenTurns[found]!;let next=current;if(evidence?.dshRequestId!==undefined&&current.dshRequestId===undefined)next={...next,dshRequestId:evidence.dshRequestId};if(current.state==='planned')next={...next,state:'uncertain'};if(next!==current)hiddenTurns=this.replaceHidden(state.record,found,next)}const diagnostic={code,message:detail(error)};if(state.record.status==='needs-recovery'&&hiddenTurns===state.record.hiddenTurns&&state.record.diagnostic?.code===diagnostic.code&&state.record.diagnostic.message===diagnostic.message)return;try{await this.save(state,{status:'needs-recovery',hiddenTurns,diagnostic})}catch{/* Do not hide the dispatch failure with a secondary journal failure. */}}
 private async recordFailedHidden(state:MutableTransaction,turnId:string,error:unknown,local:AiTurn|null):Promise<boolean>{if(local===null||local.id!==turnId||local.state!=='failed')return false;if(state.record.activeTurnId!==undefined&&state.record.activeTurnId!==turnId)return false;const{index,turn}=this.findHidden(state.record,turnId);if(turn.state==='failed')return true;if(hiddenTerminal(turn.state))return false;if(turn.dshRequestId!==undefined&&local.dshRequestId!==undefined&&turn.dshRequestId!==local.dshRequestId)return false;if(turn.dshTurn!==undefined&&local.dshTurn!==undefined&&turn.dshTurn!==local.dshTurn)return false;const failed:StoryHiddenTurnRef={...turn,state:'failed',...(turn.dshRequestId===undefined&&local.dshRequestId!==undefined?{dshRequestId:local.dshRequestId}:{}),...(turn.dshTurn===undefined&&local.dshTurn!==undefined?{dshTurn:local.dshTurn}:{})};try{await this.save(state,{status:'needs-recovery',hiddenTurns:this.replaceHidden(state.record,index,failed),activeTurnId:undefined,diagnostic:{code:'hidden-failed',message:detail(error)}});return true}catch{return false}}

 private hooks(state:MutableTransaction,turnId:string,kind:StoryHiddenTurnKind):AiDispatchHooks{return{
  turnId,
  transactionId:state.record.transactionId,
  beforeDispatch:async(evidence:AiDispatchEvidence)=>{const hidden:StoryHiddenTurnRef={turnId:evidence.turnId,kind,state:'planned',sessionId:evidence.sessionId};await this.save(state,{hiddenTurns:[...state.record.hiddenTurns,hidden],activeTurnId:evidence.turnId})},
  afterAccepted:async(evidence:AiDispatchEvidence)=>{const{index,turn}=this.findHidden(state.record,evidence.turnId);await this.save(state,{hiddenTurns:this.replaceHidden(state.record,index,{...turn,state:'dispatched',sessionId:evidence.sessionId,...(evidence.dshRequestId===undefined?{}:{dshRequestId:evidence.dshRequestId})})})},
  afterUncertain:async(evidence:AiDispatchEvidence,error:unknown)=>{await this.needsRecovery(state,evidence.turnId,error,'hidden-dispatch-uncertain',evidence)},
 }}

 private async complete(state:MutableTransaction,turnId:string,dshTurn?:number):Promise<void>{let found=this.findHidden(state.record,turnId);if(found.turn.state==='planned'){await this.save(state,{hiddenTurns:this.replaceHidden(state.record,found.index,{...found.turn,state:'dispatched'})});found=this.findHidden(state.record,turnId)}if(found.turn.state==='completed'){if(dshTurn!==undefined){if(found.turn.dshTurn!==undefined&&found.turn.dshTurn!==dshTurn)throw new Error(`hidden turn ${turnId} 的 DSH native turn 冲突：${found.turn.dshTurn} != ${dshTurn}`);if(found.turn.dshTurn===undefined)await this.save(state,{hiddenTurns:this.replaceHidden(state.record,found.index,{...found.turn,dshTurn})})}return}if(found.turn.state!=='dispatched'&&found.turn.state!=='uncertain')throw new Error(`hidden turn ${turnId} 不能完成：${found.turn.state}`);await this.save(state,{hiddenTurns:this.replaceHidden(state.record,found.index,{...found.turn,state:'completed',...(dshTurn===undefined?{}:{dshTurn})}),activeTurnId:undefined,diagnostic:undefined})}
 private async selectCanonical(state:MutableTransaction,turnId:string):Promise<void>{const{turn}=this.findHidden(state.record,turnId);if(turn.state!=='completed')throw new Error(`canonical hidden turn 尚未完成：${turnId}`);if(state.record.canonicalResultTurnId!==undefined){if(state.record.canonicalResultTurnId!==turnId)throw new Error(`transaction canonical result 冲突：${state.record.canonicalResultTurnId}`);return}await this.save(state,{canonicalResultTurnId:turnId,diagnostic:undefined})}
 private coreDetail(summary:CoreTransactionReconciliation):string{return summary.operations.map(item=>`${item.ref.operationId}:${item.state}${item.detail?`(${item.detail})`:''}`).join(', ')||'无 core operation'}
 private async coreReady(state:MutableTransaction,turnId:string|undefined,allowTerminalFailure:boolean):Promise<CoreTransactionReconciliation>{let summary:CoreTransactionReconciliation;try{summary=await this.core.reconcile(state.record)}catch(error){await this.save(state,{status:'needs-recovery',diagnostic:{code:'core-evidence-read-failed',message:detail(error)}});throw error}if(summary.readyForSocialCommit){if(turnId!==undefined)await this.selectCanonical(state,turnId);return summary}const message=this.coreDetail(summary);if(summary.deterministicNoEffectFailure&&allowTerminalFailure&&turnId!==undefined){this.ai.acknowledge(state.record.saveId,turnId);await this.save(state,{status:'failed',activeTurnId:undefined,diagnostic:{code:'core-operation-failed-no-effect',message}});throw new Error(`Core mutation 明确失败且没有 canonical effect：${message}`)}await this.save(state,{status:'needs-recovery',diagnostic:{code:'core-reconciliation-required',message}});throw new Error(`Core transaction 尚不能安全提交 social projection：${message}`)}

 private async dispatch(state:MutableTransaction,projection:StorySaveProjection,channelId:string,input:string,kind:StoryHiddenTurnKind):Promise<AiBridgeResult>{const turnId=`turn-${crypto.randomUUID()}`;let result:AiBridgeResult;try{result=kind==='initial'?await this.ai.send(projection,channelId,input,this.hooks(state,turnId,kind)):await this.ai.retry(projection,this.hooks(state,turnId,kind));if(result.turnId!==turnId)throw new Error(`AI hidden turn identity 不匹配：expected ${turnId}, got ${result.turnId??'missing'}`);await this.complete(state,turnId,result.dshTurn)}catch(error){if(state.record.hiddenTurns.some(turn=>turn.turnId===turnId)){const local=this.ai.turn(projection.saveId);const recordedFailed=await this.recordFailedHidden(state,turnId,error,local);if(!recordedFailed){const evidence=local?.id===turnId?{turnId,sessionId:local.sessionId,baseline:local.baseline,...(local.dshRequestId===undefined?{}:{dshRequestId:local.dshRequestId})}:undefined;const current=this.findHidden(state.record,turnId).turn;await this.needsRecovery(state,turnId,error,current.state==='dispatched'?'hidden-recovery-failed':'hidden-dispatch-uncertain',evidence)}}else await this.recoverBeforeHiddenDispatch(state,error);throw error}await this.coreReady(state,turnId,true);return result}

 private async recoverAi(projection:StorySaveProjection,state:MutableTransaction):Promise<RecoveredAiBridgeResult|null>{const local=this.ai.turn(projection.saveId);if(local!==null)return this.ai.recover(projection);const targetId=state.record.activeTurnId??state.record.canonicalResultTurnId??[...state.record.hiddenTurns].reverse().find(turn=>turn.state==='completed'||turn.state==='dispatched'||turn.state==='uncertain'||turn.state==='planned')?.turnId;if(targetId===undefined)return this.ai.recover(projection);const{turn}=this.findHidden(state.record,targetId);if(turn.sessionId===undefined||turn.dshRequestId===undefined)return this.ai.recover(projection);return this.ai.recoverFromEvidence(projection,{turnId:turn.turnId,sessionId:turn.sessionId,channelId:state.record.input.channelId,dshRequestId:turn.dshRequestId,...(turn.dshTurn===undefined?{}:{dshTurn:turn.dshTurn})})}

 async send(projection:StorySaveProjection,channelId:string,input:string):Promise<AiBridgeResult>{if(projection.revision<1)throw new Error('玩家提交后的 projection revision 无效');const existing=await this.open(projection.saveId);if(existing!==undefined)throw new Error(`当前存档存在未完成 transaction：${existing.transactionId}；请先恢复，不会重复发送玩家输入`);const state:MutableTransaction={record:await this.journal.prepare({saveId:projection.saveId,channelId,text:input,baseProjectionRevision:projection.revision-1})};try{await this.projections.save(projection)}catch(error){await this.recoverBeforeHiddenDispatch(state,error,'player-projection-save-uncertain');throw error}return this.dispatch(state,projection,channelId,input,'initial')}

 async recover(projection:StorySaveProjection):Promise<RecoveredAiBridgeResult|null>{const record=await this.open(projection.saveId);if(record===undefined)return this.ai.recover(projection);const state:MutableTransaction={record};const persistedCanonical=this.persistedCanonical(record,projection);if(persistedCanonical!==undefined){await this.coreReady(state,persistedCanonical,false);await this.projections.save(projection);this.ai.acknowledge(projection.saveId,persistedCanonical);await this.save(state,{status:'committed',activeTurnId:undefined,diagnostic:undefined});return null}if(record.hiddenTurns.length===0){if(record.status!=='prepared'&&record.status!=='needs-recovery')throw new Error(`transaction ${record.transactionId} 缺少 hidden evidence，状态为 ${record.status}`);const restored=await this.ensurePlayerProjection(record,projection);const result=await this.dispatch(state,restored,record.input.channelId,record.input.text,'initial');return{channelId:record.input.channelId,result,turnId:result.turnId!}}
  let recovered:RecoveredAiBridgeResult|null;try{recovered=await this.recoverAi(projection,state)}catch(error){const active=state.record.activeTurnId;if(active!==undefined&&!hiddenTerminal(this.findHidden(state.record,active).turn.state)){const local=this.ai.turn(projection.saveId);const recordedFailed=await this.recordFailedHidden(state,active,error,local);if(!recordedFailed)await this.needsRecovery(state,active,error,'hidden-recovery-failed')}throw error}if(recovered===null){const local=this.ai.turn(projection.saveId);const active=state.record.activeTurnId;if(active!==undefined&&!hiddenTerminal(this.findHidden(state.record,active).turn.state)){const recordedFailed=await this.recordFailedHidden(state,active,new Error(local?.error??`hidden turn 未产生可提交结果：${local?.state??'missing'}`),local);if(!recordedFailed)await this.needsRecovery(state,active,new Error(local===null?'本地 pending hidden turn 与可重建 durable correlation evidence 均缺失；禁止盲目重发':`hidden turn 未产生可提交结果：${local.state}`),'hidden-recovery-required',local?.id===active?{turnId:active,sessionId:local.sessionId,baseline:local.baseline,...(local.dshRequestId===undefined?{}:{dshRequestId:local.dshRequestId})}:undefined)}else{const last=state.record.hiddenTurns.at(-1);if(last?.state==='cancelled'&&state.record.canonicalResultTurnId===undefined){let summary:CoreTransactionReconciliation;try{summary=await this.core.reconcile(state.record)}catch(error){await this.save(state,{status:'needs-recovery',diagnostic:{code:'cancel-core-evidence-read-failed',message:detail(error)}});throw error}if(summary.hasCanonicalEffect){if(local?.state==='cancelled'){const result=await this.dispatch(state,projection,state.record.input.channelId,state.record.input.text,'continuation');return{channelId:state.record.input.channelId,result,turnId:result.turnId!}}await this.save(state,{status:'needs-recovery',diagnostic:{code:'cancelled-after-core-effect',message:'Core receipt 已存在，但本地 cancelled turn 不可用于 continuation；等待 restart recovery'}})}}}return null}if(!state.record.hiddenTurns.some(turn=>turn.turnId===recovered.turnId)){await this.needsRecovery(state,state.record.activeTurnId??state.record.hiddenTurns.at(-1)!.turnId,new Error(`恢复得到未知 hidden turn：${recovered.turnId}`),'hidden-identity-mismatch');throw new Error(`恢复得到的 AI turn 不属于当前 transaction：${recovered.turnId}`)}await this.complete(state,recovered.turnId,recovered.result.dshTurn);await this.coreReady(state,recovered.turnId,true);return recovered}

 async retry(projection:StorySaveProjection):Promise<AiBridgeResult>{const existing=await this.open(projection.saveId);if(existing===undefined)return this.ai.retry(projection);const state:MutableTransaction={record:existing};if(existing.canonicalResultTurnId!==undefined)throw new Error(`transaction ${existing.transactionId} 已有 canonical hidden turn ${existing.canonicalResultTurnId}；必须先完成 projection reconciliation`);const local=this.ai.turn(projection.saveId);if(local===null)throw new Error(`transaction ${existing.transactionId} 缺少本地 failed/cancelled hidden turn；必须先恢复，禁止盲目 retry`);if(local.state==='cancelled'){const summary=await this.core.reconcile(existing);if(!summary.hasCanonicalEffect)throw new Error(`transaction ${existing.transactionId} 已取消且没有已确认 canonical effect`);return this.dispatch(state,projection,state.record.input.channelId,state.record.input.text,'continuation')}if(local.state!=='failed')throw new Error(`transaction ${existing.transactionId} 的 hidden turn 状态为 ${local.state}；只有明确 failed 才允许同 transaction retry`);if(existing.activeTurnId!==undefined&&existing.activeTurnId!==local.id)throw new Error(`transaction active hidden turn 与本地 failed turn 不匹配：${existing.activeTurnId} != ${local.id}`);const otherPending=existing.hiddenTurns.find(turn=>!hiddenTerminal(turn.state)&&turn.turnId!==local.id);if(otherPending!==undefined)throw new Error(`transaction 仍有其它非终态 hidden turn：${otherPending.turnId}`);let found=this.findHidden(state.record,local.id);if(found.turn.state==='completed'||found.turn.state==='cancelled')throw new Error(`hidden turn ${local.id} 已是 ${found.turn.state}，不能作为 retry 来源`);if(found.turn.state!=='failed'){if(found.turn.dshRequestId!==undefined&&local.dshRequestId!==undefined&&found.turn.dshRequestId!==local.dshRequestId)throw new Error(`hidden turn ${local.id} 的 DSH request identity 冲突`);if(found.turn.dshTurn!==undefined&&local.dshTurn!==undefined&&found.turn.dshTurn!==local.dshTurn)throw new Error(`hidden turn ${local.id} 的 DSH native turn 冲突`);const failed:StoryHiddenTurnRef={...found.turn,state:'failed',...(found.turn.dshRequestId===undefined&&local.dshRequestId!==undefined?{dshRequestId:local.dshRequestId}:{}),...(found.turn.dshTurn===undefined&&local.dshTurn!==undefined?{dshTurn:local.dshTurn}:{})};await this.save(state,{status:'needs-recovery',hiddenTurns:this.replaceHidden(state.record,found.index,failed),activeTurnId:undefined,diagnostic:{code:'hidden-failed-retryable',message:local.error??'前一 hidden turn 已明确失败，可在同一 transaction 内 retry'}});found=this.findHidden(state.record,local.id)}if(found.turn.state!=='failed')throw new Error(`hidden turn ${local.id} 未能收敛到 failed`);return this.dispatch(state,projection,state.record.input.channelId,state.record.input.text,'retry')}

 async cancel(saveId:string):Promise<void>{await this.ai.cancel(saveId);const record=await this.open(saveId);if(record===undefined)return;const state:MutableTransaction={record};const active=record.activeTurnId;if(active===undefined){if(record.hiddenTurns.length===0&&record.status==='prepared')await this.save(state,{status:'cancelled',diagnostic:undefined});return}const{index,turn}=this.findHidden(record,active);if(hiddenTerminal(turn.state))return;const cancelled=this.replaceHidden(state.record,index,{...turn,state:'cancelled'});let summary:CoreTransactionReconciliation;try{summary=await this.core.reconcile(state.record)}catch(error){await this.save(state,{status:'needs-recovery',hiddenTurns:cancelled,activeTurnId:undefined,diagnostic:{code:'cancel-core-evidence-read-failed',message:detail(error)}});throw error}if(!summary.hasCanonicalEffect&&!summary.unresolved){await this.save(state,{status:'cancelled',hiddenTurns:cancelled,activeTurnId:undefined,diagnostic:undefined});return}await this.save(state,{status:'needs-recovery',hiddenTurns:cancelled,activeTurnId:undefined,diagnostic:{code:summary.hasCanonicalEffect?'cancelled-after-core-effect':'cancel-core-outcome-uncertain',message:this.coreDetail(summary)}})}

 async assertQuiescent(saveId:string):Promise<void>{const record=await this.open(saveId);if(record!==undefined)throw new Error(`存档存在未完成 transaction：${record.transactionId}；请先恢复或完成对账`)}

 async acknowledge(saveId:string,turnId:string):Promise<void>{const record=await this.open(saveId);if(record!==undefined){if(record.canonicalResultTurnId!==turnId)throw new Error(`open transaction ${record.transactionId} 尚未记录 canonical hidden turn ${turnId}；保留 pending turn 供恢复`);const state:MutableTransaction={record};const{turn}=this.findHidden(record,turnId);if(turn.state!=='completed')throw new Error(`canonical hidden turn 尚未完成：${turnId}`);await this.coreReady(state,turnId,false);this.ai.acknowledge(saveId,turnId);await this.save(state,{status:'committed',activeTurnId:undefined,diagnostic:undefined});return}this.ai.acknowledge(saveId,turnId)}
}
