import{describe,expect,it,vi}from'vitest'
import{StoryAiBridge}from'../src/client/ai-bridge.ts'
import{createInitialProjection}from'../src/client/initial-projection.ts'

const ok=(value:unknown,rpcId?:string)=>({...rpcId===undefined?{}:{rpcId},result:{ok:true as const,value}})

describe('uncertain hidden dispatch',()=>{
 it('persists caller turn identity before prompt and recovers from history without resending',async()=>{const save={...createInitialProjection(),saveId:'save-uncertain'};const values=new Map<string,string>([['dsh-story-ai-session:save-uncertain','session-uncertain']]);let historyCalls=0;const prompt=vi.fn(async()=>{throw new Error('transport closed after write')});const api={sessions:{create:vi.fn(async()=>ok({sessionId:'session-uncertain'})),history:vi.fn(async()=>{historyCalls+=1;if(historyCalls===1)return ok({events:[]});return ok({events:[{event:{type:'assistant/message',seq:1,data:{message:{content:[{type:'text',text:'{"messages":[{"senderId":"p-hezhou","kind":"dialogue","content":"已收到。"}]}' }]}}}},{event:{type:'turn/end',seq:2,data:{turn:1}}}]})}),prompt,cancel:vi.fn(async()=>ok({accepted:true}))},workspace:{archiveSession:vi.fn(async()=>ok({}))}};const bridge=new StoryAiBridge(api as never,{getItem:(key:string)=>values.get(key)??null,setItem:(key:string,value:string)=>{values.set(key,value)}},async()=>{});const order:string[]=[];await expect(bridge.send(save,save.selectedChannelId,'继续',{turnId:'turn-stable',beforeDispatch:async evidence=>{order.push(`before:${evidence.turnId}`);expect(evidence.dshRequestId).toBeUndefined();expect(bridge.turn(save.saveId)).toBeNull()},afterUncertain:async evidence=>{order.push(`uncertain:${evidence.turnId}`);expect(evidence.dshRequestId).toBeUndefined()}})).rejects.toThrow('transport closed after write');expect(order).toEqual(['before:turn-stable','uncertain:turn-stable']);expect(bridge.turn(save.saveId)).toMatchObject({id:'turn-stable',state:'uncertain',sessionId:'session-uncertain'});const recovered=await bridge.recover(save);expect(recovered).toMatchObject({turnId:'turn-stable',result:{messages:[{senderId:'p-hezhou',kind:'dialogue',content:'已收到。'}]}});expect(bridge.turn(save.saveId)?.state).toBe('completed');expect(prompt).toHaveBeenCalledTimes(1)})

 it('uses the accepted rpcId to select the matching native turn instead of a later history turn',async()=>{const save={...createInitialProjection(),saveId:'save-correlated'};const values=new Map<string,string>([['dsh-story-ai-session:save-correlated','session-correlated']]);let historyCalls=0;const prompt=vi.fn(async()=>ok({accepted:true},'rpc-correlated'));const target='{"messages":[{"senderId":"p-hezhou","kind":"dialogue","content":"关联成功。"}]}';const other='{"messages":[{"senderId":"p-hezhou","kind":"dialogue","content":"不应串台。"}]}';const api={sessions:{create:vi.fn(async()=>ok({sessionId:'session-correlated'})),history:vi.fn(async()=>{historyCalls+=1;if(historyCalls===1)return ok({events:[]});return ok({events:[{event:{type:'turn/start',seq:1,data:{turn:4,trigger:{kind:'message',source:{kind:'user',rpcId:'rpc-correlated'}}}}},{event:{type:'user/message',seq:2,data:{content:[{type:'text',text:'继续'}],source:{kind:'user',rpcId:'rpc-correlated'}}}},{event:{type:'assistant/message',seq:3,data:{turn:4,message:{content:[{type:'text',text:target}]}}}},{event:{type:'turn/end',seq:4,data:{turn:4}}},{event:{type:'turn/start',seq:5,data:{turn:5,trigger:{kind:'message',source:{kind:'user',rpcId:'rpc-other'}}}}},{event:{type:'user/message',seq:6,data:{content:[{type:'text',text:'别的输入'}],source:{kind:'user',rpcId:'rpc-other'}}}},{event:{type:'assistant/message',seq:7,data:{turn:5,content:[{type:'text',text:other]}}},{event:{type:'turn/end',seq:8,data:{turn:5}}}]})}),prompt,cancel:vi.fn(async()=>ok({accepted:true}))},workspace:{archiveSession:vi.fn(async()=>ok({}))}};const bridge=new StoryAiBridge(api as never,{getItem:(key:string)=>values.get(key)??null,setItem:(key:string,value:string)=>{values.set(key,value)}},async()=>{});let beforeRequestId:string|undefined;let acceptedRequestId:string|undefined;const result=await bridge.send(save,save.selectedChannelId,'继续',{turnId:'turn-correlated',beforeDispatch:async evidence=>{beforeRequestId=evidence.dshRequestId},afterAccepted:async evidence=>{acceptedRequestId=evidence.dshRequestId}});expect(beforeRequestId).toBeUndefined();expect(acceptedRequestId).toBe('rpc-correlated');expect(result).toMatchObject({turnId:'turn-correlated',dshTurn:4,messages:[{content:'关联成功。'}]});expect(result.messages[0]?.content).not.toBe('不应串台。');expect(bridge.turn(save.saveId)).toMatchObject({id:'turn-correlated',dshRequestId:'rpc-correlated',state:'completed',result:{dshTurn:4}})})

 it('keeps a running turn uncertain after a transient history failure and can recover later',async()=>{const save={...createInitialProjection(),saveId:'save-history-recover'};const values=new Map<string,string>([['dsh-story-ai-session:save-history-recover','session-history']]);let historyCalls=0;const prompt=vi.fn(async()=>ok({accepted:true}));const history=vi.fn(async()=>{historyCalls+=1;if(historyCalls===1)return ok({events:[]});if(historyCalls===2)throw new Error('history offline');return ok({events:[{event:{type:'assistant/message',seq:1,data:{message:{content:[{type:'text',text:'{"messages":[{"senderId":"p-hezhou","kind":"dialogue","content":"恢复成功。"}]}' }]}}}},{event:{type:'turn/end',seq:2,data:{turn:1}}}]})});const api={sessions:{create:vi.fn(async()=>ok({sessionId:'session-history'})),history,prompt,cancel:vi.fn(async()=>ok({accepted:true}))},workspace:{archiveSession:vi.fn(async()=>ok({}))}};const bridge=new StoryAiBridge(api as never,{getItem:(key:string)=>values.get(key)??null,setItem:(key:string,value:string)=>{values.set(key,value)}},async()=>{});await expect(bridge.send(save,save.selectedChannelId,'继续',{turnId:'turn-history'})).rejects.toThrow('history offline');expect(bridge.turn(save.saveId)).toMatchObject({id:'turn-history',state:'uncertain'});const recovered=await bridge.recover(save);expect(recovered).toMatchObject({turnId:'turn-history',result:{messages:[{content:'恢复成功。'}]}});expect(prompt).toHaveBeenCalledTimes(1)})

 it('keeps cancellation transport failure uncertain so later recovery is still possible',async()=>{const save={...createInitialProjection(),saveId:'save-cancel-ambiguous'};const values=new Map<string,string>([['dsh-story-ai-session:save-cancel-ambiguous','session-cancel-ambiguous']]);let release!:()=>void;const pause=new Promise<void>(resolve=>{release=resolve});const cancel=vi.fn(async()=>{throw new Error('cancel transport lost')});const api={sessions:{create:vi.fn(async()=>ok({sessionId:'session-cancel-ambiguous'})),history:vi.fn(async()=>ok({events:[]})),prompt:vi.fn(async()=>ok({accepted:true})),cancel},workspace:{archiveSession:vi.fn(async()=>ok({}))}};const bridge=new StoryAiBridge(api as never,{getItem:(key:string)=>values.get(key)??null,setItem:(key:string,value:string)=>{values.set(key,value)}},async()=>pause);const sending=bridge.send(save,save.selectedChannelId,'继续',{turnId:'turn-cancel-ambiguous'});await vi.waitFor(()=>expect(bridge.turn(save.saveId)?.state).toBe('running'));await expect(bridge.cancel(save.saveId)).rejects.toThrow('cancel transport lost');expect(bridge.turn(save.saveId)).toMatchObject({id:'turn-cancel-ambiguous',state:'uncertain'});release();await expect(sending).rejects.toThrow();expect(bridge.turn(save.saveId)?.state).toBe('uncertain')})

 it('allows cancellation of an uncertain local turn without dispatching another prompt',async()=>{const save={...createInitialProjection(),saveId:'save-uncertain-cancel'};const values=new Map<string,string>([['dsh-story-ai-session:save-uncertain-cancel','session-uncertain-cancel']]);const prompt=vi.fn(async()=>{throw new Error('timeout')});const cancel=vi.fn(async()=>ok({accepted:true}));const api={sessions:{create:vi.fn(async()=>ok({sessionId:'session-uncertain-cancel'})),history:vi.fn(async()=>ok({events:[]})),prompt,cancel},workspace:{archiveSession:vi.fn(async()=>ok({}))}};const bridge=new StoryAiBridge(api as never,{getItem:(key:string)=>values.get(key)??null,setItem:(key:string,value:string)=>{values.set(key,value)}},async()=>{});await expect(bridge.send(save,save.selectedChannelId,'继续',{turnId:'turn-cancel'})).rejects.toThrow('timeout');expect(bridge.turn(save.saveId)?.state).toBe('uncertain');await bridge.cancel(save.saveId);expect(cancel).toHaveBeenCalledWith({sessionId:'session-uncertain-cancel'});expect(bridge.turn(save.saveId)?.state).toBe('cancelled');expect(prompt).toHaveBeenCalledTimes(1)})
})
