import{describe,expect,it,vi}from'vitest'
import{HostTransactionJournal}from'../src/client/host-transactions.ts'
import{createPreparedTransaction,reviseTransaction}from'../src/transaction-journal.ts'

describe('host transaction journal bridge',()=>{
 it('prepares a transaction with bootstrap revision before external dispatch',async()=>{const calls:Array<{url:string;body:any}>=[];const fetcher=vi.fn(async(url:unknown,init?:RequestInit)=>{const body=JSON.parse(String(init?.body));calls.push({url:String(url),body});return new Response(JSON.stringify(body.transaction),{status:200,headers:{'content-type':'application/json'}})});const host=new HostTransactionJournal(fetcher as typeof fetch);const record=await host.prepare({transactionId:'tx-prepare',saveId:'save-a',channelId:'scene-main',text:'继续',baseProjectionRevision:7,now:new Date('2026-08-30T08:00:00.000Z')});expect(calls).toHaveLength(1);expect(calls[0]).toMatchObject({url:'/story-engine/api/transactions/save-a/tx-prepare',body:{expectedRevision:-1}});expect(record).toMatchObject({transactionId:'tx-prepare',status:'prepared',revision:0,baseProjectionRevision:7})})
 it('loads and filters nonterminal transactions for restart recovery',async()=>{const prepared=await createPreparedTransaction({transactionId:'tx-open',saveId:'save-a',channelId:'scene-main',text:'A',baseProjectionRevision:0});const committed=reviseTransaction(await createPreparedTransaction({transactionId:'tx-done',saveId:'save-a',channelId:'scene-main',text:'B',baseProjectionRevision:0}),{status:'committed'});const fetcher=vi.fn(async()=>new Response(JSON.stringify({transactions:[prepared,committed]}),{status:200,headers:{'content-type':'application/json'}}));const host=new HostTransactionJournal(fetcher as typeof fetch);expect((await host.listOpen('save-a')).map(record=>record.transactionId)).toEqual(['tx-open'])})
 it('surfaces host idempotency conflicts without inventing a replacement transaction id',async()=>{const record=await createPreparedTransaction({transactionId:'tx-conflict',saveId:'save-a',channelId:'scene-main',text:'A',baseProjectionRevision:0});const host=new HostTransactionJournal((async()=>new Response(JSON.stringify({error:'transaction 幂等冲突：input identity 不可修改'}),{status:409,headers:{'content-type':'application/json'}}))as typeof fetch);await expect(host.save(record,true)).rejects.toThrow('transaction 幂等冲突');expect(record.transactionId).toBe('tx-conflict')})
 it('treats 204 as an absent transaction record',async()=>{const host=new HostTransactionJournal((async()=>new Response(null,{status:204}))as typeof fetch);await expect(host.load('save-a','tx-missing')).resolves.toBeUndefined()})
})
