import{describe,expect,it,vi}from'vitest'
import{createPreparedTransaction,reviseTransaction,type StoryTransactionRecord}from'../src/transaction-journal.ts'
import{PlayerTransactionCoordinator}from'../src/client/player-transaction-coordinator.ts'
import{appendAiMessages,appendPlayerMessage}from'../src/client/story-domain.ts'
import{createInitialProjection}from'../src/client/initial-projection.ts'

function harness(events:string[]=[]){
 let records:StoryTransactionRecord[]=[]
 const journal={
  listOpen:vi.fn(async(saveId:string)=>records.filter(record=>record.saveId===saveId&&!['committed','cancelled','failed'].includes(record.status))),
  prepare:vi.fn(async(input:any)=>{events.push('prepare');const record=await createPreparedTransaction({...input,transactionId:'tx-test',now:new Date('2026-09-01T00:00:00.000Z')});records=[...records,record];return record}),
  save:vi.fn(async(record:StoryTransactionRecord)=>{const index=records.findIndex(item=>item.transactionId===record.transactionId);if(index<0)records.push(record);else records[index]=record;events.push(`journal:${record.status}:${record.hiddenTurns.at(-1)?.state??'none'}`);return record}),
 }
 return{journal,get record(){return records.at(-1)!},set record(value:StoryTransactionRecord){records=[value]}}
}

function submitted(){const base={...createInitialProjection(),saveId:'save-tx'};return appendPlayerMessage(base,base.selectedChannelId,'继续')}
const aiResult={raw:'{}',messages:[{senderId:'p-hezhou',kind:'dialogue' as const,content:'收到。'}]}

describe('player transaction coordinator',()=>{
 it('persists accepted request and native turn evidence before acknowledging the hidden result',async()=>{const events:string[]=[];const state=harness(events);const projection={save:vi.fn(async()=>{events.push('projection')})};const ai={send:vi.fn(async(_save:any,_channel:string,_input:string,hooks:any)=>{const evidence={turnId:hooks.turnId,sessionId:'session-1',baseline:2};await hooks.beforeDispatch(evidence);events.push('prompt');await hooks.afterAccepted({...evidence,dshRequestId:'rpc-1'});return{...aiResult,turnId:evidence.turnId,dshTurn:3}}),recover:vi.fn(),retry:vi.fn(),cancel:vi.fn(),turn:vi.fn(),acknowledge:vi.fn(()=>{events.push('ack')})};const coordinator=new PlayerTransactionCoordinator(state.journal as never,projection as never,ai as never);const save=submitted();const result=await coordinator.send(save,save.selectedChannelId,'继续');expect(result.turnId).toMatch(/^turn-/);expect(state.record).toMatchObject({status:'prepared',baseProjectionRevision:0,canonicalResultTurnId:result.turnId,hiddenTurns:[{turnId:result.turnId,kind:'initial',state:'completed',sessionId:'session-1',dshRequestId:'rpc-1',dshTurn:3}]});expect(events).toEqual(['prepare','projection','journal:prepared:planned','prompt','journal:prepared:dispatched','journal:prepared:completed']);await coordinator.acknowledge(save.saveId,result.turnId!);expect(state.record.status).toBe('committed');expect(events.slice(-2)).toEqual(['ack','journal:committed:completed'])})

 it('keeps the journal open when hidden acknowledge fails',async()=>{const state=harness();const save=submitted();const prepared=await createPreparedTransaction({transactionId:'tx-ack-failure',saveId:save.saveId,channelId:save.selectedChannelId,text:'继续',baseProjectionRevision:0});const planned=reviseTransaction(prepared,{hiddenTurns:[{turnId:'turn-ack-failure',kind:'initial',state:'planned',sessionId:'session-ack-failure'}],activeTurnId:'turn-ack-failure'});const dispatched=reviseTransaction(planned,{hiddenTurns:[{turnId:'turn-ack-failure',kind:'initial',state:'dispatched',sessionId:'session-ack-failure'}],activeTurnId:'turn-ack-failure'});state.record=reviseTransaction(dispatched,{hiddenTurns:[{turnId:'turn-ack-failure',kind:'initial',state:'completed',sessionId:'session-ack-failure'}],activeTurnId:undefined,canonicalResultTurnId:'turn-ack-failure'});const ai={send:vi.fn(),recover:vi.fn(),retry:vi.fn(),cancel:vi.fn(),turn:vi.fn(),acknowledge:vi.fn(()=>{throw new Error('ack failed')})};const coordinator=new PlayerTransactionCoordinator(state.journal as never,{save:vi.fn()} as never,ai as never);await expect(coordinator.acknowledge(save.saveId,'turn-ack-failure')).rejects.toThrow('ack failed');expect(state.record.status).toBe('prepared');expect(state.record.canonicalResultTurnId).toBe('turn-ack-failure')})

 it('finalizes a journal when the canonical result is already durable in the projection',async()=>{const events:string[]=[];const state=harness(events);const save=submitted();const prepared=await createPreparedTransaction({transactionId:'tx-projected',saveId:save.saveId,channelId:save.selectedChannelId,text:'继续',baseProjectionRevision:0});const planned=reviseTransaction(prepared,{hiddenTurns:[{turnId:'turn-projected',kind:'initial',state:'planned',sessionId:'session-projected'}],activeTurnId:'turn-projected'});const dispatched=reviseTransaction(planned,{hiddenTurns:[{turnId:'turn-projected',kind:'initial',state:'dispatched',sessionId:'session-projected'}],activeTurnId:'turn-projected'});state.record=reviseTransaction(dispatched,{hiddenTurns:[{turnId:'turn-projected',kind:'initial',state:'completed',sessionId:'session-projected'}],activeTurnId:undefined,canonicalResultTurnId:'turn-projected'});const durable=appendAiMessages(save,save.selectedChannelId,aiResult.messages,new Date('2026-09-01T00:01:00.000Z'),'turn-projected');const recover=vi.fn();const ai={send:vi.fn(),recover,retry:vi.fn(),cancel:vi.fn(),turn:vi.fn(),acknowledge:vi.fn(()=>{events.push('ack')})};const coordinator=new PlayerTransactionCoordinator(state.journal as never,{save:vi.fn()} as never,ai as never);await expect(coordinator.recover(durable)).resolves.toBeNull();expect(recover).not.toHaveBeenCalled();expect(state.record.status).toBe('committed');expect(events.slice(-2)).toEqual(['ack','journal:committed:completed'])})

 it('records one needs-recovery revision when rc.2 prompt acceptance is uncertain and blocks retry',async()=>{const events:string[]=[];const state=harness(events);const projection={save:vi.fn(async()=>{events.push('projection')})};const retry=vi.fn();const ai={send:vi.fn(async(_save:any,_channel:string,_input:string,hooks:any)=>{const evidence={turnId:hooks.turnId,sessionId:'session-uncertain',baseline:4};await hooks.beforeDispatch(evidence);events.push('prompt');const error=new Error('socket closed');await hooks.afterUncertain(evidence,error);throw error}),recover:vi.fn(),retry,cancel:vi.fn(),turn:vi.fn(()=>({state:'uncertain'})),acknowledge:vi.fn()};const coordinator=new PlayerTransactionCoordinator(state.journal as never,projection as never,ai as never);const save=submitted();await expect(coordinator.send(save,save.selectedChannelId,'继续')).rejects.toThrow('socket closed');expect(state.record).toMatchObject({status:'needs-recovery',revision:2,hiddenTurns:[{kind:'initial',state:'uncertain',sessionId:'session-uncertain'}],diagnostic:{code:'hidden-dispatch-uncertain'}});expect(events.filter(event=>event.startsWith('journal:'))).toEqual(['journal:prepared:planned','journal:needs-recovery:uncertain']);await expect(coordinator.retry(save)).rejects.toThrow('只有明确 failed 才允许同 transaction retry');expect(retry).not.toHaveBeenCalled()})

 it('can continue the same prepared transaction after a crash before hidden dispatch',async()=>{const events:string[]=[];const state=harness(events);const save=submitted();await state.journal.prepare({saveId:save.saveId,channelId:save.selectedChannelId,text:'继续',baseProjectionRevision:0});const ai={send:vi.fn(async(_save:any,_channel:string,_input:string,hooks:any)=>{const evidence={turnId:hooks.turnId,sessionId:'session-resume',baseline:1};await hooks.beforeDispatch(evidence);events.push('prompt');await hooks.afterAccepted(evidence);return{...aiResult,turnId:evidence.turnId}}),recover:vi.fn(),retry:vi.fn(),cancel:vi.fn(),turn:vi.fn(),acknowledge:vi.fn()};const coordinator=new PlayerTransactionCoordinator(state.journal as never,{save:vi.fn()} as never,ai as never);const recovered=await coordinator.recover(save);expect(recovered?.turnId).toBe(state.record.canonicalResultTurnId);expect(ai.send).toHaveBeenCalledTimes(1);expect(state.journal.prepare).toHaveBeenCalledTimes(1);expect(state.record.hiddenTurns[0]).toMatchObject({kind:'initial',state:'completed',sessionId:'session-resume'})})

 it('never resends player input when a persisted hidden attempt loses its local pending record on rc.2',async()=>{const state=harness();const save=submitted();const prepared=await createPreparedTransaction({transactionId:'tx-existing',saveId:save.saveId,channelId:save.selectedChannelId,text:'继续',baseProjectionRevision:0});state.record=reviseTransaction(prepared,{hiddenTurns:[{turnId:'turn-existing',kind:'initial',state:'planned',sessionId:'session-existing'}],activeTurnId:'turn-existing'});const send=vi.fn();const ai={send,recover:vi.fn(async()=>null),retry:vi.fn(),cancel:vi.fn(),turn:vi.fn(()=>null),acknowledge:vi.fn()};const coordinator=new PlayerTransactionCoordinator(state.journal as never,{save:vi.fn()} as never,ai as never);await expect(coordinator.recover(save)).resolves.toBeNull();expect(send).not.toHaveBeenCalled();expect(state.record).toMatchObject({status:'needs-recovery',hiddenTurns:[{turnId:'turn-existing',state:'uncertain'}],diagnostic:{code:'hidden-recovery-required'}})})

 it('records a recovery diagnostic when history reconciliation itself fails',async()=>{const state=harness();const save=submitted();const prepared=await createPreparedTransaction({transactionId:'tx-history-error',saveId:save.saveId,channelId:save.selectedChannelId,text:'继续',baseProjectionRevision:0});const planned=reviseTransaction(prepared,{hiddenTurns:[{turnId:'turn-history-error',kind:'initial',state:'planned',sessionId:'session-history-error'}],activeTurnId:'turn-history-error'});state.record=reviseTransaction(planned,{hiddenTurns:[{turnId:'turn-history-error',kind:'initial',state:'dispatched',sessionId:'session-history-error'}],activeTurnId:'turn-history-error'});const ai={send:vi.fn(),recover:vi.fn(async()=>{throw new Error('history unavailable')}),retry:vi.fn(),cancel:vi.fn(),turn:vi.fn(),acknowledge:vi.fn()};const coordinator=new PlayerTransactionCoordinator(state.journal as never,{save:vi.fn()} as never,ai as never);await expect(coordinator.recover(save)).rejects.toThrow('history unavailable');expect(state.record).toMatchObject({status:'needs-recovery',hiddenTurns:[{turnId:'turn-history-error',state:'dispatched'}],diagnostic:{code:'hidden-recovery-failed',message:'history unavailable'}});expect(ai.send).not.toHaveBeenCalled()})

 it('does not clear a hidden pending result when the open journal points at another canonical turn',async()=>{const state=harness();const save=submitted();const prepared=await createPreparedTransaction({transactionId:'tx-ack-mismatch',saveId:save.saveId,channelId:save.selectedChannelId,text:'继续',baseProjectionRevision:0});const planned=reviseTransaction(prepared,{hiddenTurns:[{turnId:'turn-one',kind:'initial',state:'planned',sessionId:'session-one'}],activeTurnId:'turn-one'});const dispatched=reviseTransaction(planned,{hiddenTurns:[{turnId:'turn-one',kind:'initial',state:'dispatched',sessionId:'session-one'}],activeTurnId:'turn-one'});state.record=reviseTransaction(dispatched,{hiddenTurns:[{turnId:'turn-one',kind:'initial',state:'completed',sessionId:'session-one'}],activeTurnId:undefined,canonicalResultTurnId:'turn-one'});const acknowledge=vi.fn();const ai={send:vi.fn(),recover:vi.fn(),retry:vi.fn(),cancel:vi.fn(),turn:vi.fn(),acknowledge};const coordinator=new PlayerTransactionCoordinator(state.journal as never,{save:vi.fn()} as never,ai as never);await expect(coordinator.acknowledge(save.saveId,'turn-other')).rejects.toThrow('尚未记录 canonical hidden turn');expect(state.record.status).toBe('prepared');expect(acknowledge).not.toHaveBeenCalled()})
})
