import{describe,expect,it,vi}from'vitest'
import{createPreparedTransaction,reviseTransaction,type StoryTransactionRecord}from'../src/transaction-journal.ts'
import{PlayerTransactionCoordinator}from'../src/client/player-transaction-coordinator.ts'
import{appendPlayerMessage,type StorySaveProjection}from'../src/client/story-domain.ts'
import{createInitialProjection}from'../src/client/initial-projection.ts'

function journalWith(record:StoryTransactionRecord){let current=record;return{port:{listOpen:vi.fn(async()=>['committed','cancelled','failed'].includes(current.status)?[]:[current]),prepare:vi.fn(),save:vi.fn(async(next:StoryTransactionRecord)=>{current=next;return next})},get record(){return current}}}
function baseProjection():StorySaveProjection{return{...createInitialProjection(),saveId:'save-prepared-recovery'}}
const aiResult={raw:'{}',messages:[{senderId:'p-hezhou',kind:'dialogue' as const,content:'继续。'}]}

describe('prepared transaction projection recovery',()=>{
 it('rebuilds and persists the player projection before hidden dispatch',async()=>{const base=baseProjection();const prepared=await createPreparedTransaction({transactionId:'tx-prepared-rebuild',saveId:base.saveId,channelId:base.selectedChannelId,text:'继续',baseProjectionRevision:base.revision});const state=journalWith(prepared);const events:string[]=[];let savedProjection:StorySaveProjection|undefined;const projections={save:vi.fn(async(value:StorySaveProjection)=>{savedProjection=value;events.push(`projection:${value.revision}`)})};const ai={send:vi.fn(async(projection:StorySaveProjection,_channel:string,_input:string,hooks:any)=>{expect(projection.revision).toBe(1);expect(projection.messages.at(-1)).toMatchObject({channelId:base.selectedChannelId,content:'继续',canonStatus:'committed'});events.push('dispatch');const evidence={turnId:hooks.turnId,sessionId:'session-prepared',baseline:0};await hooks.beforeDispatch(evidence);await hooks.afterAccepted({...evidence,dshRequestId:'rpc-prepared'});return{...aiResult,turnId:evidence.turnId,dshTurn:1}}),recover:vi.fn(),recoverFromEvidence:vi.fn(),retry:vi.fn(),cancel:vi.fn(),turn:vi.fn(()=>null),acknowledge:vi.fn()};const coordinator=new PlayerTransactionCoordinator(state.port as never,projections as never,ai as never);const recovered=await coordinator.recover(base);expect(events[0]).toBe('projection:1');expect(events[1]).toBe('dispatch');expect(savedProjection?.revision).toBe(1);expect(recovered?.turnId).toBe(state.record.canonicalResultTurnId);expect(state.record.hiddenTurns[0]).toMatchObject({kind:'initial',state:'completed',dshRequestId:'rpc-prepared',dshTurn:1});expect(ai.send).toHaveBeenCalledTimes(1)})

 it('fails closed when the projection advanced outside the prepared transaction',async()=>{const base=baseProjection();const prepared=await createPreparedTransaction({transactionId:'tx-prepared-conflict',saveId:base.saveId,channelId:base.selectedChannelId,text:'继续',baseProjectionRevision:base.revision});const state=journalWith(prepared);const submitted=appendPlayerMessage(base,base.selectedChannelId,'另一条输入');const projections={save:vi.fn()};const ai={send:vi.fn(),recover:vi.fn(),recoverFromEvidence:vi.fn(),retry:vi.fn(),cancel:vi.fn(),turn:vi.fn(()=>null),acknowledge:vi.fn()};const coordinator=new PlayerTransactionCoordinator(state.port as never,projections as never,ai as never);await expect(coordinator.recover(submitted)).rejects.toThrow('玩家 projection 无法安全恢复');expect(projections.save).not.toHaveBeenCalled();expect(ai.send).not.toHaveBeenCalled();expect(state.record.status).toBe('prepared')})
})
