import{mkdtemp}from'node:fs/promises'
import{tmpdir}from'node:os'
import{join}from'node:path'
import{describe,expect,it}from'vitest'
import{apply}from'../src/index.ts'
import{coreStepKey}from'../src/core-step-journal.ts'
import{createPreparedTransaction,reviseTransaction}from'../src/transaction-journal.ts'

function request(method:string,url:string,payload?:unknown,origin:string|undefined='http://localhost'):any{const chunks=payload===undefined?[]:[Buffer.from(JSON.stringify(payload),'utf8')];return{method,url,headers:{host:'localhost',...(origin===undefined?{}:{origin})},async *[Symbol.asyncIterator](){for(const chunk of chunks)yield chunk}}}
function responseCapture():{res:any;snapshot:()=>{status:number;headers:Record<string,unknown>;body:unknown}}{let status=0;const headers:Record<string,unknown>={};let raw='';return{res:{writeHead(code:number,values?:Record<string,unknown>){status=code;Object.assign(headers,values)},setHeader(name:string,value:unknown){headers[name.toLowerCase()]=value},end(value?:unknown){if(value!==undefined)raw+=String(value)}},snapshot:()=>({status,headers,body:raw===''?undefined:JSON.parse(raw)})}}

describe('transaction host API',()=>{
 it('supports PUT, GET, list, optimistic conflict, collision, path errors, and same-origin writes',async()=>{const root=await mkdtemp(join(tmpdir(),'story-tx-api-'));const registrations:any[]=[];const ctx={webServer:{register:(entry:any)=>{registrations.push(entry);return()=>{}}},effect:(factory:()=>unknown)=>factory(),on:()=>()=>{}} as any;apply(ctx,{runtimeRoot:root,storyRuntimeRoot:join(root,'runtime'),packsRoot:join(root,'packs')});const route=registrations.find(entry=>entry.path==='/story-engine/api/transactions');expect(route).toBeDefined();const first=await createPreparedTransaction({transactionId:'tx:api',saveId:'save-a',channelId:'scene-main',text:'A',baseProjectionRevision:0,now:new Date('2026-08-30T08:00:00.000Z')});
  let capture=responseCapture();await route.handler(request('PUT','/story-engine/api/transactions/save-a/tx%3Aapi',{expectedRevision:-1,transaction:first}),capture.res);expect(capture.snapshot()).toMatchObject({status:200,body:{transactionId:'tx:api',revision:0}})
  capture=responseCapture();await route.handler(request('GET','/story-engine/api/transactions/save-a/tx%3Aapi',undefined,undefined),capture.res);expect(capture.snapshot()).toMatchObject({status:200,body:{transactionId:'tx:api'}})
  capture=responseCapture();await route.handler(request('GET','/story-engine/api/transactions/save-a',undefined,undefined),capture.res);expect(capture.snapshot()).toMatchObject({status:200,body:{transactions:[{transactionId:'tx:api'}]}})
  const collision=await createPreparedTransaction({transactionId:'tx:api',saveId:'save-a',channelId:'scene-main',text:'B',baseProjectionRevision:0,now:new Date('2026-08-30T08:00:00.000Z')});capture=responseCapture();await route.handler(request('PUT','/story-engine/api/transactions/save-a/tx%3Aapi',{expectedRevision:-1,transaction:collision}),capture.res);expect(capture.snapshot()).toMatchObject({status:409,body:{error:expect.stringContaining('幂等冲突')}})
  const advanced=reviseTransaction(first,{diagnostic:{code:'advanced',message:'first winner'}},new Date('2026-08-30T08:00:01.000Z'));capture=responseCapture();await route.handler(request('PUT','/story-engine/api/transactions/save-a/tx%3Aapi',{expectedRevision:0,transaction:advanced}),capture.res);expect(capture.snapshot()).toMatchObject({status:200,body:{revision:1}})
  const stale=reviseTransaction(first,{diagnostic:{code:'stale',message:'second writer'}},new Date('2026-08-30T08:00:02.000Z'));capture=responseCapture();await route.handler(request('PUT','/story-engine/api/transactions/save-a/tx%3Aapi',{expectedRevision:0,transaction:stale}),capture.res);expect(capture.snapshot()).toMatchObject({status:409,body:{error:expect.stringContaining('版本冲突')}})
  for(const path of['/story-engine/api/transactions/save-a/%E0%A4%A','/story-engine/api/transactions/save-a/tx/extra','/story-engine/api/transactions/save-a/','/story-engine/api/transactions//save-a','/story-engine/api/transactionsX/save-a']){capture=responseCapture();await route.handler(request('GET',path,undefined,undefined),capture.res);expect(capture.snapshot().status).toBe(400)}
  const other=await createPreparedTransaction({transactionId:'tx-cross-origin',saveId:'save-a',channelId:'scene-main',text:'C',baseProjectionRevision:0});capture=responseCapture();await route.handler(request('PUT','/story-engine/api/transactions/save-a/tx-cross-origin',{expectedRevision:-1,transaction:other},'https://evil.example'),capture.res);expect(capture.snapshot().status).toBe(403)
 })

 it('persists a core operation ref through the tools/execute hook before invoking the tool body',async()=>{const root=await mkdtemp(join(tmpdir(),'story-core-hook-'));const registrations:any[]=[];const listeners=new Map<string,Function>();const ctx={webServer:{register:(entry:any)=>{registrations.push(entry);return()=>{}}},effect:(factory:()=>unknown)=>factory(),on:(event:string,listener:Function)=>{listeners.set(event,listener);return()=>listeners.delete(event)}} as any;apply(ctx,{runtimeRoot:root,storyRuntimeRoot:join(root,'runtime'),packsRoot:join(root,'packs')});const route=registrations.find(entry=>entry.path==='/story-engine/api/transactions');const toolExecute=listeners.get('tools/execute');expect(toolExecute).toBeDefined();
  const initial=await createPreparedTransaction({transactionId:'tx-core-hook',saveId:'save-a',channelId:'scene-main',text:'继续',baseProjectionRevision:0,now:new Date('2026-09-03T00:00:00.000Z')});let capture=responseCapture();await route.handler(request('PUT','/story-engine/api/transactions/save-a/tx-core-hook',{expectedRevision:-1,transaction:initial}),capture.res);expect(capture.snapshot().status).toBe(200);const linked=reviseTransaction(initial,{hiddenTurns:[{turnId:'turn-core-hook',kind:'initial',state:'planned',sessionId:'session-core-hook'}],activeTurnId:'turn-core-hook'},new Date('2026-09-03T00:00:01.000Z'));capture=responseCapture();await route.handler(request('PUT','/story-engine/api/transactions/save-a/tx-core-hook',{expectedRevision:0,transaction:linked}),capture.res);expect(capture.snapshot().status).toBe(200)
  let bodyCalled=false;await toolExecute!({name:'story_commit_state',arguments:{operation_id:'op-core-hook',transaction_id:'tx-core-hook'},agent:{id:'session-core-hook'}},async()=>{bodyCalled=true;return{ok:true}});expect(bodyCalled).toBe(true);capture=responseCapture();await route.handler(request('GET','/story-engine/api/transactions/save-a/tx-core-hook',undefined,undefined),capture.res);expect(capture.snapshot()).toMatchObject({status:200,body:{revision:2,operationRefs:[{stepKey:coreStepKey('tx-core-hook','story_commit_state','op-core-hook'),operationId:'op-core-hook'}]}})
  bodyCalled=false;await expect(toolExecute!({name:'story_advance_scene',arguments:{operation_id:'op-wrong',transaction_id:'tx-other'},agent:{id:'session-core-hook'}},async()=>{bodyCalled=true;return{ok:true}})).rejects.toThrow('transaction identity 冲突');expect(bodyCalled).toBe(false)
 })
})
