import{mkdir,mkdtemp,readdir,writeFile}from'node:fs/promises'
import{tmpdir}from'node:os'
import{join}from'node:path'
import{describe,expect,it}from'vitest'
import{createPreparedTransaction,reviseTransaction}from'../src/transaction-journal.ts'
import{StoryTransactionStore}from'../src/transaction-store.ts'

describe('transaction journal store',()=>{
 it('persists atomically and accepts an identical same-revision replay',async()=>{const store=new StoryTransactionStore(await mkdtemp(join(tmpdir(),'story-tx-')));const record=await createPreparedTransaction({transactionId:'tx-one',saveId:'save-a',channelId:'scene-main',text:'前进',baseProjectionRevision:3});expect(await store.write('save-a','tx-one',-1,record)).toEqual(record);expect(await store.write('save-a','tx-one',-1,structuredClone(record))).toEqual(record);expect(await store.read('save-a','tx-one')).toEqual(record)})
 it('uses canonical percent-encoded filenames for transaction ids that contain Windows-reserved colon characters',async()=>{const root=await mkdtemp(join(tmpdir(),'story-tx-win-'));const store=new StoryTransactionStore(root);const record=await createPreparedTransaction({transactionId:'tx:step:1',saveId:'save-a',channelId:'scene-main',text:'前进',baseProjectionRevision:0});await store.write('save-a','tx:step:1',-1,record);expect(await readdir(join(root,'transaction-journal','save-a'))).toEqual(['tx%3Astep%3A1.json']);expect((await store.list('save-a'))[0]?.transactionId).toBe('tx:step:1')})
 it('rejects the same transaction id with a different player input without replacing the original',async()=>{const store=new StoryTransactionStore(await mkdtemp(join(tmpdir(),'story-tx-collision-')));const first=await createPreparedTransaction({transactionId:'tx-collision',saveId:'save-a',channelId:'scene-main',text:'A',baseProjectionRevision:0});const second=await createPreparedTransaction({transactionId:'tx-collision',saveId:'save-a',channelId:'scene-main',text:'B',baseProjectionRevision:0});await store.write('save-a','tx-collision',-1,first);await expect(store.write('save-a','tx-collision',-1,second)).rejects.toThrow('幂等冲突');expect(await store.read('save-a','tx-collision')).toEqual(first)})
 it('serializes concurrent updates so only one writer advances a revision',async()=>{const store=new StoryTransactionStore(await mkdtemp(join(tmpdir(),'story-tx-race-')));const initial=await createPreparedTransaction({transactionId:'tx-race',saveId:'save-a',channelId:'scene-main',text:'继续',baseProjectionRevision:0});await store.write('save-a','tx-race',-1,initial);const a=reviseTransaction(initial,{hiddenTurns:[{requestId:'req-a',kind:'initial',state:'planned'}]},new Date('2026-08-30T08:00:01.000Z'));const b=reviseTransaction(initial,{hiddenTurns:[{requestId:'req-b',kind:'initial',state:'planned'}]},new Date('2026-08-30T08:00:02.000Z'));const results=await Promise.allSettled([store.write('save-a','tx-race',0,a),store.write('save-a','tx-race',0,b)]);expect(results.filter(result=>result.status==='fulfilled')).toHaveLength(1);expect(results.filter(result=>result.status==='rejected')).toHaveLength(1);expect((await store.read('save-a','tx-race'))?.revision).toBe(1)})
 it('keeps records isolated by save id',async()=>{const store=new StoryTransactionStore(await mkdtemp(join(tmpdir(),'story-tx-save-')));const a=await createPreparedTransaction({transactionId:'tx-same',saveId:'save-a',channelId:'scene-main',text:'A',baseProjectionRevision:0});const b=await createPreparedTransaction({transactionId:'tx-same',saveId:'save-b',channelId:'scene-main',text:'B',baseProjectionRevision:0});await store.write('save-a','tx-same',-1,a);await store.write('save-b','tx-same',-1,b);expect((await store.list('save-a')).map(record=>record.input.text)).toEqual(['A']);expect((await store.list('save-b')).map(record=>record.input.text)).toEqual(['B'])})
 it('fails closed when a journal file is corrupt instead of silently skipping recovery evidence',async()=>{const root=await mkdtemp(join(tmpdir(),'story-tx-corrupt-'));const directory=join(root,'transaction-journal','save-a');await mkdir(directory,{recursive:true});await writeFile(join(directory,'tx-broken.json'),'{broken','utf8');const store=new StoryTransactionStore(root);await expect(store.list('save-a')).rejects.toThrow()})
})
