import{mkdir,mkdtemp,readdir,writeFile}from'node:fs/promises'
import{tmpdir}from'node:os'
import{join}from'node:path'
import{describe,expect,it}from'vitest'
import{createPreparedTransaction,reviseTransaction}from'../src/transaction-journal.ts'
import{StoryTransactionStore}from'../src/transaction-store.ts'

describe('transaction journal store',()=>{
 it('persists atomically, survives store restart, and accepts an identical same-revision replay',async()=>{const root=await mkdtemp(join(tmpdir(),'story-tx-'));const store=new StoryTransactionStore(root);const record=await createPreparedTransaction({transactionId:'tx-one',saveId:'save-a',channelId:'scene-main',text:'前进',baseProjectionRevision:3});expect(await store.write('save-a','tx-one',-1,record)).toEqual(record);expect(await store.write('save-a','tx-one',-1,structuredClone(record))).toEqual(record);const names=await readdir(join(root,'transaction-journal','save-a'));expect(names).toHaveLength(1);expect(names[0]?.endsWith('.json')).toBe(true);expect(names.some(name=>name.endsWith('.tmp'))).toBe(false);expect(await new StoryTransactionStore(root).read('save-a','tx-one')).toEqual(record)})
 it('uses bounded Windows-safe filenames for reserved characters, device names, and maximum-length transaction ids',async()=>{const root=await mkdtemp(join(tmpdir(),'story-tx-win-'));const store=new StoryTransactionStore(root);const ids=['tx:step:1','CON',`a${':'.repeat(127)}`];for(const transactionId of ids){const record=await createPreparedTransaction({transactionId,saveId:'save-a',channelId:'scene-main',text:transactionId,baseProjectionRevision:0});await store.write('save-a',transactionId,-1,record)}const names=await readdir(join(root,'transaction-journal','save-a'));expect(names).toHaveLength(3);for(const name of names){expect(name.startsWith('tx-')).toBe(true);expect(name.endsWith('.json')).toBe(true);expect(name.includes(':')).toBe(false);expect(name.length).toBeLessThan(200)}expect((await store.list('save-a')).map(record=>record.transactionId).sort()).toEqual([...ids].sort())})
 it('rejects the same transaction id with a different player input without replacing the original',async()=>{const store=new StoryTransactionStore(await mkdtemp(join(tmpdir(),'story-tx-collision-')));const first=await createPreparedTransaction({transactionId:'tx-collision',saveId:'save-a',channelId:'scene-main',text:'A',baseProjectionRevision:0});const second=await createPreparedTransaction({transactionId:'tx-collision',saveId:'save-a',channelId:'scene-main',text:'B',baseProjectionRevision:0});await store.write('save-a','tx-collision',-1,first);await expect(store.write('save-a','tx-collision',-1,second)).rejects.toThrow('幂等冲突');expect(await store.read('save-a','tx-collision')).toEqual(first)})
 it('rejects bootstrap records that bypass the prepared lifecycle',async()=>{const store=new StoryTransactionStore(await mkdtemp(join(tmpdir(),'story-tx-bootstrap-')));const base=await createPreparedTransaction({transactionId:'tx-bootstrap',saveId:'save-a',channelId:'scene-main',text:'继续',baseProjectionRevision:0});const forged={...base,hiddenTurns:[{turnId:'turn-forged',dshRequestId:'req-forged',kind:'initial' as const,state:'completed' as const,sessionId:'session-1',dshTurn:1}],canonicalResultTurnId:'turn-forged'};await expect(store.write('save-a','tx-bootstrap',-1,forged)).rejects.toThrow('初始 transaction 不能预填 hidden turn evidence');expect(await store.read('save-a','tx-bootstrap')).toBeUndefined()})
 it('rejects a durable input fingerprint that does not match the stored input',async()=>{const store=new StoryTransactionStore(await mkdtemp(join(tmpdir(),'story-tx-fingerprint-')));const record=await createPreparedTransaction({transactionId:'tx-fingerprint',saveId:'save-a',channelId:'scene-main',text:'A',baseProjectionRevision:0});await expect(store.write('save-a','tx-fingerprint',-1,{...record,inputFingerprint:'0'.repeat(64)})).rejects.toThrow('inputFingerprint 与 transaction input 不一致')})
 it('serializes concurrent updates so only one writer advances a revision',async()=>{const store=new StoryTransactionStore(await mkdtemp(join(tmpdir(),'story-tx-race-')));const initial=await createPreparedTransaction({transactionId:'tx-race',saveId:'save-a',channelId:'scene-main',text:'继续',baseProjectionRevision:0});await store.write('save-a','tx-race',-1,initial);const a=reviseTransaction(initial,{hiddenTurns:[{turnId:'turn-a',dshRequestId:'req-a',kind:'initial',state:'planned'}]},new Date('2026-08-30T08:00:01.000Z'));const b=reviseTransaction(initial,{hiddenTurns:[{turnId:'turn-b',dshRequestId:'req-b',kind:'initial',state:'planned'}]},new Date('2026-08-30T08:00:02.000Z'));const results=await Promise.allSettled([store.write('save-a','tx-race',0,a),store.write('save-a','tx-race',0,b)]);expect(results.filter(result=>result.status==='fulfilled')).toHaveLength(1);expect(results.filter(result=>result.status==='rejected')).toHaveLength(1);expect((await store.read('save-a','tx-race'))?.revision).toBe(1)})
 it('keeps records isolated by save id',async()=>{const store=new StoryTransactionStore(await mkdtemp(join(tmpdir(),'story-tx-save-')));const a=await createPreparedTransaction({transactionId:'tx-same',saveId:'save-a',channelId:'scene-main',text:'A',baseProjectionRevision:0});const b=await createPreparedTransaction({transactionId:'tx-same',saveId:'save-b',channelId:'scene-main',text:'B',baseProjectionRevision:0});await store.write('save-a','tx-same',-1,a);await store.write('save-b','tx-same',-1,b);expect((await store.list('save-a')).map(record=>record.input.text)).toEqual(['A']);expect((await store.list('save-b')).map(record=>record.input.text)).toEqual(['B'])})
 it('fails closed when a canonical journal file contains malformed JSON',async()=>{const root=await mkdtemp(join(tmpdir(),'story-tx-corrupt-json-'));const directory=join(root,'transaction-journal','save-a');await mkdir(directory,{recursive:true});const name=`tx-${Buffer.from('tx-broken','utf8').toString('base64url')}.json`;await writeFile(join(directory,name),'{broken','utf8');const store=new StoryTransactionStore(root);await expect(store.list('save-a')).rejects.toThrow()})
 it('fails closed when a journal is structurally valid JSON but violates terminal-state invariants',async()=>{const root=await mkdtemp(join(tmpdir(),'story-tx-corrupt-state-'));const directory=join(root,'transaction-journal','save-a');await mkdir(directory,{recursive:true});const base=await createPreparedTransaction({transactionId:'tx-semantic-broken',saveId:'save-a',channelId:'scene-main',text:'继续',baseProjectionRevision:0});const forged={...base,status:'committed',hiddenTurns:[{turnId:'turn-1',dshRequestId:'req-1',kind:'initial',state:'planned'}],activeTurnId:'turn-1'};const name=`tx-${Buffer.from(base.transactionId,'utf8').toString('base64url')}.json`;await writeFile(join(directory,name),`${JSON.stringify(forged)}\n`,'utf8');const store=new StoryTransactionStore(root);await expect(store.list('save-a')).rejects.toThrow('终态 committed 不能保留 activeTurnId')})
})
