import{describe,expect,it}from'vitest'
import{createPreparedTransaction,fingerprintTransactionInput,reviseTransaction,validateTransactionRecord}from'../src/transaction-journal.ts'

describe('transaction journal contract',()=>{
 it('creates a stable prepared intent with a deterministic input fingerprint',async()=>{const now=new Date('2026-08-30T08:00:00.000Z');const record=await createPreparedTransaction({transactionId:'tx-test-1',saveId:'save-a',channelId:'scene-main',text:'  向灯塔走去  ',baseProjectionRevision:4,now});expect(record).toMatchObject({transactionId:'tx-test-1',saveId:'save-a',input:{channelId:'scene-main',text:'向灯塔走去'},baseProjectionRevision:4,status:'prepared',revision:0,createdAt:now.toISOString()});expect(record.inputFingerprint).toBe(await fingerprintTransactionInput('save-a','scene-main','向灯塔走去'));expect(record.inputFingerprint).toMatch(/^[a-f0-9]{64}$/)})
 it('keeps hidden evidence monotonic and only accepts a completed canonical-result turn',async()=>{const base=await createPreparedTransaction({transactionId:'tx-turns',saveId:'save-a',channelId:'scene-main',text:'继续',baseProjectionRevision:0,now:new Date('2026-08-30T08:00:00.000Z')});const planned=reviseTransaction(base,{hiddenTurns:[{requestId:'req-1',kind:'initial',state:'planned'}],activeRequestId:'req-1'},new Date('2026-08-30T08:00:01.000Z'));const dispatched=reviseTransaction(planned,{hiddenTurns:[{requestId:'req-1',kind:'initial',state:'dispatched',sessionId:'session-1'}]},new Date('2026-08-30T08:00:02.000Z'));expect(()=>reviseTransaction(dispatched,{hiddenTurns:[{requestId:'req-1',kind:'initial',state:'planned',sessionId:'session-1'}]},new Date('2026-08-30T08:00:03.000Z'))).toThrow('幂等冲突');expect(()=>validateTransactionRecord({...dispatched,canonicalResultTurnId:'turn-1'})).toThrow('未引用已知 hidden turn');const completed=reviseTransaction(dispatched,{hiddenTurns:[{requestId:'req-1',kind:'initial',state:'completed',sessionId:'session-1',turnId:'turn-1'}],activeRequestId:undefined,canonicalResultTurnId:'turn-1'},new Date('2026-08-30T08:00:04.000Z'));expect(completed.canonicalResultTurnId).toBe('turn-1')})
 it('does not permit a terminal transaction to acquire a later revision',async()=>{const base=await createPreparedTransaction({transactionId:'tx-terminal',saveId:'save-a',channelId:'scene-main',text:'结束',baseProjectionRevision:0});const committed=reviseTransaction(base,{status:'committed'});expect(()=>reviseTransaction(committed,{diagnostic:{code:'late',message:'late write'}})).toThrow('终态 committed 不可产生新 revision')})
 it('rejects changing the input identity under one transaction id',async()=>{const base=await createPreparedTransaction({transactionId:'tx-input',saveId:'save-a',channelId:'scene-main',text:'A',baseProjectionRevision:0});const forged=validateTransactionRecord({...base,input:{...base.input,text:'B'},inputFingerprint:await fingerprintTransactionInput('save-a','scene-main','B'),revision:1,updatedAt:new Date(Date.parse(base.updatedAt)+1000).toISOString()});expect(()=>reviseTransaction(base,{input:forged.input} as never)).toThrow();})
})
