import{mkdir,readFile,readdir,rename,writeFile}from'node:fs/promises'
import{join}from'node:path'
import{isDeepStrictEqual}from'node:util'
import{assertInitialTransactionRecord,assertSaveId,assertTransactionId,assertTransactionUpdate,fingerprintTransactionInput,validateTransactionRecord,type StoryTransactionRecord}from'./transaction-journal.ts'

export class StoryTransactionStore{
 private readonly queues=new Map<string,Promise<void>>()
 constructor(private readonly root:string){}
 private directory(saveId:string):string{assertSaveId(saveId);return join(this.root,'transaction-journal',saveId)}
 private filename(transactionId:string):string{assertTransactionId(transactionId);return`tx-${Buffer.from(transactionId,'utf8').toString('base64url')}.json`}
 private transactionIdFromFilename(name:string):string{if(!name.startsWith('tx-')||!name.endsWith('.json'))throw new Error(`transaction journal 文件名格式无效：${name}`);const encoded=name.slice(3,-5);let transactionId:string;try{transactionId=Buffer.from(encoded,'base64url').toString('utf8')}catch{throw new Error(`transaction journal 文件名编码无效：${name}`)}assertTransactionId(transactionId);if(this.filename(transactionId)!==name)throw new Error(`transaction journal 文件名非规范编码：${name}`);return transactionId}
 private path(saveId:string,transactionId:string):string{return join(this.directory(saveId),this.filename(transactionId))}
 private async validate(value:unknown):Promise<StoryTransactionRecord>{const record=validateTransactionRecord(value);const fingerprint=await fingerprintTransactionInput(record.saveId,record.input.channelId,record.input.text);if(record.inputFingerprint!==fingerprint)throw new Error('inputFingerprint 与 transaction input 不一致');return record}
 private async exclusive<T>(saveId:string,transactionId:string,work:()=>Promise<T>):Promise<T>{const key=`${saveId}:${transactionId}`;const previous=this.queues.get(key)??Promise.resolve();let release!:()=>void;const current=new Promise<void>(resolve=>{release=resolve});const queued=previous.then(()=>current);this.queues.set(key,queued);await previous;try{return await work()}finally{release();if(this.queues.get(key)===queued)this.queues.delete(key)}}
 async read(saveId:string,transactionId:string):Promise<StoryTransactionRecord|undefined>{assertSaveId(saveId);assertTransactionId(transactionId);try{const value=await this.validate(JSON.parse(await readFile(this.path(saveId,transactionId),'utf8')));if(value.saveId!==saveId||value.transactionId!==transactionId)throw new Error('transaction journal 路径身份不匹配');return value}catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT')return undefined;throw error}}
 async list(saveId:string):Promise<StoryTransactionRecord[]>{assertSaveId(saveId);const directory=this.directory(saveId);const names=await readdir(directory).catch(error=>{if((error as NodeJS.ErrnoException).code==='ENOENT')return[]as string[];throw error});const records:StoryTransactionRecord[]=[];for(const name of names){if(!name.endsWith('.json'))continue;const transactionId=this.transactionIdFromFilename(name);const record=await this.read(saveId,transactionId);if(record===undefined)throw new Error(`transaction journal 在列表期间消失：${transactionId}`);records.push(record)}return records.sort((a,b)=>a.createdAt.localeCompare(b.createdAt)||a.transactionId.localeCompare(b.transactionId))}
 async write(saveId:string,transactionId:string,expectedRevision:number,value:unknown):Promise<StoryTransactionRecord>{assertSaveId(saveId);assertTransactionId(transactionId);if(!Number.isInteger(expectedRevision)||expectedRevision< -1)throw new Error('expectedRevision 无效');const next=await this.validate(value);if(next.saveId!==saveId||next.transactionId!==transactionId)throw new Error('transaction journal 路径身份不匹配');if(next.revision!==expectedRevision+1)throw new Error('transaction 新版本无效');return this.exclusive(saveId,transactionId,async()=>{const current=await this.read(saveId,transactionId);const revision=current===undefined?-1:current.revision;if(current!==undefined&&revision===next.revision){if(isDeepStrictEqual(current,next))return current;assertTransactionUpdate(current,next);throw new Error(`transaction 版本冲突：revision ${revision} 的内容不同`)}if(revision!==expectedRevision)throw new Error(`transaction 版本冲突：当前 ${revision}，提交基于 ${expectedRevision}`);if(current===undefined)assertInitialTransactionRecord(next);else assertTransactionUpdate(current,next);const path=this.path(saveId,transactionId);await mkdir(this.directory(saveId),{recursive:true});const temporary=`${path}.${process.pid}.${Math.random().toString(36).slice(2)}.tmp`;await writeFile(temporary,`${JSON.stringify(next,null,2)}\n`,'utf8');await rename(temporary,path);return next})}
}
