import type { Context } from '@deepseek-ai/cordis'
import { defineTool } from '@deepseek-ai/dsh-tools'
import type {} from '@deepseek-ai/dsh-system-prompt'
import '@deepseek-ai/dsh-user-questions'
import { ContentIndex } from './content-index.js'
import { ContentPackLoader } from './content-pack.js'
import { EntityIndex } from './entity-index.js'
import { SerialStateStore } from './serial-state.js'
import { discoverAndLoadEpisodes, validateCrossReferences } from './script-loader.js'
import type { EpisodeScript, OperationIdentity, WorkEvent, WorkResult } from './serial-types.js'

export const name='dsh-story-engine'
export const inject=['tools','systemPrompt','userQuestions']
export interface Config{packRoot:string;runtimeRoot:string}
const objectOutput={schema:{type:'object',additionalProperties:true} as const,render:(_args:unknown,value:unknown)=>[{type:'text' as const,text:JSON.stringify(value,null,2)}]}
const arrayOutput={schema:{type:'array',items:{type:'object',additionalProperties:true}} as const,render:objectOutput.render}
function sessionId(exec:{agent?:{session?:{id?:unknown}}}):string{const id=exec.agent?.session?.id;if(!id)throw new Error('Story 工具只能在 Agent 会话中使用');return String(id)}
const operationParameters={operation_id:{type:'string',required:true},transaction_id:{type:'string'}} as const
function operationIdentity(args:{operation_id?:unknown;transaction_id?:unknown}):OperationIdentity{
 if(typeof args.operation_id!=='string')throw new Error('operation_id 必须是字符串')
 if(args.transaction_id!==undefined&&typeof args.transaction_id!=='string')throw new Error('transaction_id 必须是字符串')
 return{operationId:args.operation_id,...(args.transaction_id===undefined?{}:{transactionId:args.transaction_id})}
}
const highImpactWords=['死亡','永久','关键','主线','道德','感情','恋爱','背叛','失踪','重伤','重大']
function isHighImpact(work:WorkEvent):boolean{return work.result==='disaster'||highImpactWords.some(word=>`${work.name} ${work.stateEffects.join(' ')}`.includes(word))}

export async function apply(ctx:Context,config:Config):Promise<void>{
 const pack=await new ContentPackLoader().load(config.packRoot);const content=new ContentIndex(pack.documents);const entities=new EntityIndex(pack.documents);const states=new SerialStateStore(config.runtimeRoot,pack.manifest.id,pack.initialState,{id:pack.manifest.id,name:pack.manifest.name,version:pack.manifest.version,language:pack.manifest.language,license:pack.manifest.license,player:pack.manifest.player})
 const extraPrompt=pack.documents.filter(x=>x.kind==='prompt').map(x=>x.text).join('\n\n');const controlled=pack.manifest.player.controlledCharacters.join('、')
 ctx.systemPrompt.section({name:`story:${pack.manifest.id}:game-master`,order:55,text:`你是互动文字游戏《${pack.manifest.name}》的主持人。玩家控制：${controlled}。${pack.manifest.player.aiMayControlPlayer?'内容包允许你在必要时描写玩家角色。':'绝不替玩家角色决定、说话、行动或描述内心。'}你控制 NPC、世界和行动后果。每轮先读状态；内容包事实先检索；重大选择提供 2–4 个选项并允许自由输入；越界时必须先暂停、修订、校验再继续。工作内只简报普通事件，高影响事件升级为工作外场景。每个会修改 canonical runtime state 的原子工具调用使用独立稳定 operation_id；同一原子写操作的 retry 必须复用原 operation_id，不同写操作不得共用。${extraPrompt?`\n\n${extraPrompt}`:''}`})
 const register=(tool:any)=>ctx.tools.register(defineTool(tool))
 register({name:'story_get_pack_info',description:'读取当前内容包信息。',parameters:{},output:objectOutput,async execute(){return pack.manifest}})
 register({name:'story_search_content',description:'检索内容包原文。',parameters:{query:{type:'string',required:true},kind:{type:'string'},limit:{type:'number'}},output:arrayOutput,async execute(a:any){return content.search(a.query,a.limit,a.kind)}})
 register({name:'story_get_record',description:'按记录 ID 读取完整原文。',parameters:{id:{type:'string',required:true}},output:objectOutput,async execute(a:any){return content.get(a.id)}})
 register({name:'story_get_entity',description:'按名字或 ID 查找人物。',parameters:{query:{type:'string',required:true},limit:{type:'number'}},output:arrayOutput,async execute(a:any){return entities.find(a.query,a.limit)}})
 register({name:'story_read_state',description:'读取完整游戏状态。',parameters:{},output:objectOutput,async execute(_a:any,e:any){return states.read(sessionId(e))}})
 register({name:'story_commit_state',description:'以版本锁提交普通状态变化，不能修改三层真相和引擎字段；返回稳定 operation receipt。',parameters:{...operationParameters,expected_version:{type:'number',required:true},reason:{type:'string',required:true},changes:{type:'object',required:true,additionalProperties:true}},output:objectOutput,async execute(a:any,e:any){return(await states.commit(sessionId(e),a.expected_version,a.changes,a.reason,operationIdentity(a))).receipt}})
 register({name:'story_create_checkpoint',description:'创建显式检查点。',parameters:{label:{type:'string',required:true}},output:objectOutput,async execute(a:any,e:any){return states.checkpoint(sessionId(e),a.label)}})
 register({name:'story_list_checkpoints',description:'列出检查点。',parameters:{},output:arrayOutput,async execute(_a:any,e:any){return states.checkpoints(sessionId(e))}})
 register({name:'story_advance_scene',description:'兼容旧包的场景推进；返回稳定 operation receipt。',parameters:{...operationParameters,expected_version:{type:'number',required:true},scene:{type:'string',required:true},summary:{type:'string',required:true}},output:objectOutput,async execute(a:any,e:any){return(await states.advanceScene(sessionId(e),a.expected_version,a.scene,a.summary,operationIdentity(a))).receipt}})
 register({name:'story_present_choice',description:'显示 2–4 个互斥选项并允许自定义回答。',parameters:{choice_id:{type:'string',required:true},header:{type:'string',required:true},question:{type:'string',required:true},options:{type:'array',required:true,items:{type:'object',additionalProperties:false,properties:{label:{type:'string',required:true},description:{type:'string',required:true}}}}},output:objectOutput,async execute(a:any,e:any){if(a.options.length<2||a.options.length>4)throw new Error('剧情选择必须包含 2–4 个选项');const result=await ctx.userQuestions.ask({questions:[{id:a.choice_id,header:a.header,question:a.question,options:a.options}],...(e.agent?{agent:e.agent}:{}),signal:e.signal});const answer=result.answers[0];return{choiceId:a.choice_id,selected:[...(answer?.selected??[])],...(answer?.custom?{custom:answer.custom}:{})}}})

 register({name:'story_list_episode_scripts',description:'加载并列出全部分季分集剧本。',parameters:{},output:arrayOutput,async execute(){const episodes=await discoverAndLoadEpisodes(config.packRoot);return[...episodes.values()].map(p=>p.index.byEpisode[p.script.episodeId]).sort((a,b)=>a.season-b.season||a.episode-b.episode)}})
 register({name:'story_get_episode_script',description:'读取一集完整剧本。',parameters:{episode_id:{type:'string',required:true}},output:objectOutput,async execute(a:any){const episodes=await discoverAndLoadEpisodes(config.packRoot);const found=episodes.get(a.episode_id);if(!found)throw new Error(`剧本不存在：${a.episode_id}`);return found.script}})
 register({name:'story_validate_episode_scripts',description:'校验全部剧本格式、连续性、引用与可达性。',parameters:{},output:objectOutput,async execute(){const episodes=await discoverAndLoadEpisodes(config.packRoot);return{valid:true,count:episodes.size,diagnostics:validateCrossReferences(episodes)}}})
 register({name:'story_initialize_episode_state',description:'把已校验剧本索引写入当前会话；返回稳定 operation receipt。',parameters:{...operationParameters,expected_version:{type:'number',required:true}},output:objectOutput,async execute(a:any,e:any){const episodes=await discoverAndLoadEpisodes(config.packRoot);return(await states.initializeScripts(sessionId(e),a.expected_version,episodes,operationIdentity(a))).receipt}})
 register({name:'story_enter_episode_scene',description:'进入指定集的正式场景并创建幂等检查点；返回稳定 operation receipt。',parameters:{...operationParameters,expected_version:{type:'number',required:true},episode_id:{type:'string',required:true},scene_id:{type:'string',required:true},branch_id:{type:'string'}},output:objectOutput,async execute(a:any,e:any){const episodes=await discoverAndLoadEpisodes(config.packRoot);const parsed=episodes.get(a.episode_id);if(!parsed)throw new Error('剧本不存在');return(await states.enterEpisodeScene(sessionId(e),a.expected_version,parsed.script,a.scene_id,a.branch_id??'main',operationIdentity(a))).receipt}})
 register({name:'story_record_script_choice',description:'验证并记录当前场景真实可用的玩家选择；返回稳定 operation receipt。',parameters:{...operationParameters,expected_version:{type:'number',required:true},episode_id:{type:'string',required:true},scene_id:{type:'string',required:true},choice_id:{type:'string',required:true},selected_option_ids:{type:'array',required:true,items:{type:'string'}},free_input:{type:'string'},consequences:{type:'array',required:true,items:{type:'string'}}},output:objectOutput,async execute(a:any,e:any){const episodes=await discoverAndLoadEpisodes(config.packRoot);const parsed=episodes.get(a.episode_id);if(!parsed)throw new Error('剧本不存在');return(await states.recordChoice(sessionId(e),a.expected_version,parsed.script,a.scene_id,a.choice_id,a.selected_option_ids,a.free_input,a.consequences,operationIdentity(a))).receipt}})
 register({name:'story_record_work_event',description:'记录普通派遣简报；高影响事件不落盘并要求升级为工作外场景。普通事件返回稳定 operation receipt。',parameters:{...operationParameters,expected_version:{type:'number',required:true},event_id:{type:'string',required:true},name:{type:'string',required:true},assigned_actors:{type:'array',required:true,items:{type:'string'}},result:{type:'string',required:true},state_effects:{type:'array',required:true,items:{type:'string'}}},output:objectOutput,async execute(a:any,e:any){const allowed:WorkResult[]=['perfect','success','partial','failure','disaster'];if(!allowed.includes(a.result))throw new Error('result 无效');const work:WorkEvent={id:a.event_id,name:a.name,assignedActors:a.assigned_actors,result:a.result,stateEffects:a.state_effects};if(isHighImpact(work))return{escalated:true,recorded:false,event:work,reason:'涉及重大后果，必须写成工作外场景'};const execution=await states.recordWorkEvent(sessionId(e),a.expected_version,work,operationIdentity(a));return{escalated:false,recorded:true,event:work,stateVersion:execution.receipt.stateVersion,operation:execution.receipt}}})
 register({name:'story_pause_for_revision',description:'玩家输入实质性越界时，在产生后果前暂停；返回稳定 operation receipt。',parameters:{...operationParameters,expected_version:{type:'number',required:true},user_input:{type:'string',required:true},reason:{type:'string',required:true},resume_point:{type:'string',required:true}},output:objectOutput,async execute(a:any,e:any){return(await states.pauseForRevision(sessionId(e),a.expected_version,a.reason,a.user_input,a.resume_point,operationIdentity(a))).receipt}})
 register({name:'story_submit_script_revision',description:'提交完整修订剧本；只写运行时修订目录，校验成功后恢复；返回稳定 operation receipt。',parameters:{...operationParameters,expected_version:{type:'number',required:true},reason:{type:'string',required:true},script:{type:'object',required:true,additionalProperties:true}},output:objectOutput,async execute(a:any,e:any){return(await states.submitRevision(sessionId(e),a.expected_version,a.script as EpisodeScript,a.reason,operationIdentity(a))).receipt}})
 register({name:'story_record_episode_summary',description:'从已记录选择生成集末总结；未选项由引擎计算，不显示隐藏路线或联网比例；返回含 summary 的稳定 operation receipt。',parameters:{...operationParameters,expected_version:{type:'number',required:true},episode_id:{type:'string',required:true},scene_id:{type:'string',required:true},consequences:{type:'array',required:true,items:{type:'string'}},relationship_changes:{type:'array',items:{type:'string'}}},output:objectOutput,async execute(a:any,e:any){const episodes=await discoverAndLoadEpisodes(config.packRoot);const parsed=episodes.get(a.episode_id);if(!parsed)throw new Error('剧本不存在');return(await states.recordEpisodeSummary(sessionId(e),a.expected_version,parsed.script,a.scene_id,a.consequences,a.relationship_changes??[],operationIdentity(a))).receipt}})
}
