import { mkdtemp, mkdir, readFile, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import { discoverAndLoadEpisodes, validateCrossReferences, validateScriptSchema } from './script-loader.js'
import { SerialStateStore } from './serial-state.js'
import type { EpisodeScript, EpisodeSummary, OperationIdentity } from './serial-types.js'

let operationSequence=0
function op(prefix='op',transactionId?:string):OperationIdentity{return{operationId:`${prefix}-${++operationSequence}`,...(transactionId?{transactionId}:{})}}

function episode(id='s1e1', version=1): EpisodeScript { return {
 schemaVersion:1,episodeId:id,season:1,episode:1,title:'开篇',status:'validated',
 continuity:{startsAfter:'',fixedFacts:['既有事实不可倒改'],openThreads:['线索'],seasonDecision:{mode:'continue_current_season',reason:'继续当前冲突'}},
 scenes:[
  {id:'opening',mode:'off_work',title:'开场',entryConditions:[],cast:['主角'],fixedFacts:[],characterGoals:{主角:'调查'},secrets:['幕后真相'],beats:['出现线索'],choices:[{id:'route',prompt:'怎么做？',allowFreeInput:true,options:[{id:'follow',label:'跟踪',consequenceTags:['risk'],nextScene:'ending'},{id:'wait',label:'等待',consequenceTags:['safe'],nextScene:'ending'}]}],dialogueAnchors:[],improvisationEnvelope:['闲聊'],exitConditions:['完成选择'],transitions:[],stateEffects:[]},
  {id:'ending',mode:'off_work',title:'结尾',entryConditions:['完成选择'],cast:['主角'],fixedFacts:[],characterGoals:{},secrets:[],beats:['收束'],choices:[],dialogueAnchors:[],improvisationEnvelope:[],exitConditions:['结束'],transitions:[],stateEffects:[]}
 ],ending:{completionConditions:['ending 完成'],recap:{includeChosen:true,includeDeclined:true,includeConsequences:true,showNetworkPercentages:false,revealHiddenBranches:false}},revision:{version,outOfScriptPolicy:'immediate_pause_revise_validate_resume',history:[{version,reason:'初稿',changedAt:'2026-01-01T00:00:00.000Z'}]}
}}

describe('v0.7 serial scripts',()=>{
 it('validates, indexes and discovers episode JSON files',async()=>{const root=await mkdtemp(join(tmpdir(),'dsh-v07-'));const dir=join(root,'story','episodes');await mkdir(dir,{recursive:true});await writeFile(join(dir,'s1e1.json'),JSON.stringify(episode()),'utf8');const episodes=await discoverAndLoadEpisodes(root);expect(episodes.size).toBe(1);expect(episodes.get('s1e1')?.index.sceneToEpisode.get('opening')).toBe('s1e1');expect(validateCrossReferences(episodes)).toEqual([])})
 it('keeps old packs without an episodes directory compatible',async()=>{const root=await mkdtemp(join(tmpdir(),'dsh-v06-pack-'));expect((await discoverAndLoadEpisodes(root)).size).toBe(0)})
 it('rejects missing transition targets and unreachable scenes',()=>{const value=episode();value.scenes[0].choices[0].options[0].nextScene='missing';const parsed=validateScriptSchema(value);expect(validateCrossReferences(new Map([['s1e1',parsed]])).join(' ')).toContain('不存在场景')})
 it('uses optimistic locking and protects authored truth',async()=>{const root=await mkdtemp(join(tmpdir(),'dsh-state-'));const store=new SerialStateStore(root,'pack',{world:{weather:'rain'}});const first=await store.read('s');expect(first._engine.stateVersion).toBe(0);const next=await store.commit('s',0,{world:{weather:'sun'}},'change',op('commit'));expect(next.receipt.stateVersion).toBe(1);await expect(store.commit('s',0,{world:{}},'stale',op('stale'))).rejects.toThrow('版本冲突');await expect(store.commit('s',1,{authoredScript:{}},'forbidden',op('forbidden'))).rejects.toThrow('保护字段')})
 it('allows only one of two distinct concurrent writes based on the same version',async()=>{const root=await mkdtemp(join(tmpdir(),'dsh-lock-'));const store=new SerialStateStore(root,'pack',{});const results=await Promise.allSettled([store.commit('s',0,{flags:{a:true}},'a',op('a')),store.commit('s',0,{flags:{b:true}},'b',op('b'))]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect(results.filter(r=>r.status==='rejected')).toHaveLength(1)})
 it('records real choices and computes declined options without hidden data',async()=>{const root=await mkdtemp(join(tmpdir(),'dsh-summary-'));const store=new SerialStateStore(root,'pack',{});const script=episode();await store.enterEpisodeScene('s',0,script,'opening','main',op('enter'));await store.recordChoice('s',1,script,'opening','route',['follow'],undefined,['被发现'],op('choice'));await store.enterEpisodeScene('s',2,script,'ending','main',op('ending'));const result=await store.recordEpisodeSummary('s',3,script,'ending',['线索公开'],[],op('summary'));const summary=(result.receipt.result as {summary:EpisodeSummary}).summary;expect(summary.chosen[0].selected[0].label).toBe('跟踪');expect(summary.declined[0].options).toEqual([{id:'wait',label:'等待'}]);expect(JSON.stringify(summary)).not.toContain('幕后真相')})
 it('rejects choices from a valid but non-current episode or scene',async()=>{const root=await mkdtemp(join(tmpdir(),'dsh-choice-boundary-'));const store=new SerialStateStore(root,'pack',{});const current=episode('s1e1');await store.enterEpisodeScene('s',0,current,'opening','main',op('enter'));const otherEpisode=episode('s1e2');await expect(store.recordChoice('s',1,otherEpisode,'opening','route',['follow'],undefined,[],op('other-episode'))).rejects.toThrow('当前游玩场景');const sameEpisode=episode('s1e1');sameEpisode.scenes[1].choices=[{id:'ending-route',prompt:'结束？',allowFreeInput:true,options:[{id:'leave',label:'离开',consequenceTags:[]}]}];await expect(store.recordChoice('s',1,sameEpisode,'ending','ending-route',['leave'],undefined,[],op('other-scene'))).rejects.toThrow('当前游玩场景');const state=await store.read('s');expect(state._engine.stateVersion).toBe(1);expect(state.playedCanon.choices).toEqual([])})
 it('marks only actually entered episode scenes as completed canon',async()=>{const root=await mkdtemp(join(tmpdir(),'dsh-played-scenes-'));const store=new SerialStateStore(root,'pack',{});const script=episode();script.scenes[0].choices[0].options[1].nextScene='alternate';script.scenes.push({id:'alternate',mode:'off_work',title:'未选择分支',entryConditions:['等待'],cast:['主角'],fixedFacts:[],characterGoals:{},secrets:['未游玩秘密'],beats:['另一条路线'],choices:[],dialogueAnchors:[],improvisationEnvelope:[],exitConditions:['结束'],transitions:[],stateEffects:[]});await store.enterEpisodeScene('s',0,script,'opening','main',op('enter'));await store.recordChoice('s',1,script,'opening','route',['follow'],undefined,[],op('choice'));await store.enterEpisodeScene('s',2,script,'ending','main',op('ending'));await store.recordEpisodeSummary('s',3,script,'ending',[],[],op('summary'));const state=await store.read('s');expect(state.playedCanon.completedScenes).toEqual(['opening','ending']);expect(state.playedCanon.completedScenes).not.toContain('alternate')})
 it('does not write invalid revisions and resumes only after valid revision',async()=>{const root=await mkdtemp(join(tmpdir(),'dsh-revision-'));const store=new SerialStateStore(root,'pack',{});await store.pauseForRevision('s',0,'越界','去月球','opening',op('pause'));const invalid=episode('s1e1',2);invalid.scenes[0].choices[0].options[0].nextScene='missing';await expect(store.submitRevision('s',1,invalid,'扩写',op('invalid-revision'))).rejects.toThrow('校验失败');expect((await store.read('s')).playedCanon.pauseState).toBe('paused-for-revision');const valid=episode('s1e1',2);const execution=await store.submitRevision('s',1,valid,'扩写',op('valid-revision'));const state=await store.read('s');expect(execution.receipt.stateVersion).toBe(2);expect(state.playedCanon.pauseState).toBe('running');expect(await readFile(state.authoredScript.scripts.s1e1.scriptPath,'utf8')).toContain('"version": 2')})
 it('emits lossless-JSON events without undefined-valued keys (DSH tool output contract)',async()=>{const root=await mkdtemp(join(tmpdir(),'dsh-lossless-'));const store=new SerialStateStore(root,'pack',{});const script=episode();await store.enterEpisodeScene('s',0,script,'opening','main',op('enter'));const entered=await store.read('s');await store.recordChoice('s',1,script,'opening','route',['follow'],undefined,['被发现'],op('choice'));const recorded=await store.read('s');await store.enterEpisodeScene('s',2,script,'ending','main',op('ending'));await store.recordEpisodeSummary('s',3,script,'ending',['线索公开'],[],op('summary'));const summarized=await store.read('s');for(const state of [entered,recorded,summarized]){for(const event of state.playedCanon.events){for(const key of Object.keys(event) as Array<keyof typeof event>){expect(event[key]).not.toBeUndefined()};expect(JSON.parse(JSON.stringify(event))).toEqual(event)}}})
})

describe('Stage D core operation idempotency',()=>{
 it('replays a committed operation before version checks without duplicating canon or checkpoints',async()=>{const root=await mkdtemp(join(tmpdir(),'dsh-op-replay-'));const store=new SerialStateStore(root,'pack',{});const script=episode();const identity={operationId:'enter-opening-001',transactionId:'tx-player-001'};const first=await store.enterEpisodeScene('s',0,script,'opening','main',identity);const replay=await store.enterEpisodeScene('s',0,script,'opening','main',identity);expect(first.replayed).toBe(false);expect(replay.replayed).toBe(true);expect(replay.receipt).toEqual(first.receipt);const state=await store.read('s');expect(state._engine.stateVersion).toBe(1);expect(state.playedCanon.events.filter(item=>item.type==='scene_entered')).toHaveLength(1);expect(await store.checkpoints('s')).toHaveLength(1)})
 it('rejects the same operation id with a different payload without changing the original receipt',async()=>{const root=await mkdtemp(join(tmpdir(),'dsh-op-conflict-'));const store=new SerialStateStore(root,'pack',{});const identity={operationId:'commit-conflict-001'};const first=await store.commit('s',0,{flags:{a:true}},'first',identity);await expect(store.commit('s',1,{flags:{b:true}},'second',identity)).rejects.toThrow('幂等操作冲突');const state=await store.read('s');expect(state._engine.stateVersion).toBe(1);expect(state.flags).toEqual({a:true});expect(state._engine.operationReceipts[identity.operationId]).toEqual(first.receipt)})
 it('does not create a receipt when a new operation loses optimistic locking',async()=>{const root=await mkdtemp(join(tmpdir(),'dsh-op-version-'));const store=new SerialStateStore(root,'pack',{});await store.commit('s',0,{flags:{a:true}},'first',{operationId:'first-write-001'});await expect(store.commit('s',0,{flags:{b:true}},'stale',{operationId:'stale-write-001'})).rejects.toThrow('版本冲突');const state=await store.read('s');expect(state._engine.operationReceipts['stale-write-001']).toBeUndefined();expect(Object.keys(state._engine.operationReceipts)).toEqual(['first-write-001'])})
 it('serializes concurrent duplicate operation ids so the effect is applied once',async()=>{const root=await mkdtemp(join(tmpdir(),'dsh-op-concurrent-'));const store=new SerialStateStore(root,'pack',{});const identity={operationId:'same-write-001'};const [a,b]=await Promise.all([store.commit('s',0,{flags:{once:true}},'same',identity),store.commit('s',0,{flags:{once:true}},'same',identity)]);expect([a.replayed,b.replayed].sort()).toEqual([false,true]);expect(a.receipt).toEqual(b.receipt);const state=await store.read('s');expect(state._engine.stateVersion).toBe(1);expect(Object.keys(state._engine.operationReceipts)).toEqual(['same-write-001'])})
 it('treats distinct operation ids with identical payloads as distinct logical writes',async()=>{const root=await mkdtemp(join(tmpdir(),'dsh-op-distinct-'));const store=new SerialStateStore(root,'pack',{});await store.commit('s',0,{flags:{same:true}},'same',{operationId:'write-a-001'});await store.commit('s',1,{flags:{same:true}},'same',{operationId:'write-b-001'});const state=await store.read('s');expect(state._engine.stateVersion).toBe(2);expect(Object.keys(state._engine.operationReceipts).sort()).toEqual(['write-a-001','write-b-001'])})
 it('keeps consumed operation ids across checkpoint restore so stale retries cannot resurrect rolled-back effects',async()=>{const root=await mkdtemp(join(tmpdir(),'dsh-op-restore-'));const store=new SerialStateStore(root,'pack',{});const checkpoint=await store.checkpoint('s','base');const identity={operationId:'before-restore-001'};const first=await store.commit('s',0,{flags:{temporary:true}},'temporary',identity);const restored=await store.restoreCheckpoint('s',checkpoint.id);expect(restored._engine.stateVersion).toBe(2);expect(restored.flags).toEqual({});expect(restored._engine.operationReceipts[identity.operationId]).toEqual(first.receipt);const replay=await store.commit('s',2,{flags:{temporary:true}},'temporary',identity);expect(replay.replayed).toBe(true);const after=await store.read('s');expect(after._engine.stateVersion).toBe(2);expect(after.flags).toEqual({})})
 it('rejects checkpoint restore when the same operation id has conflicting receipt evidence',async()=>{const root=await mkdtemp(join(tmpdir(),'dsh-op-restore-conflict-'));const store=new SerialStateStore(root,'pack',{});const identity={operationId:'restore-conflict-001'};await store.commit('s',0,{flags:{kept:true}},'kept',identity);const checkpoint=await store.checkpoint('s','after-commit');const raw=JSON.parse(await readFile(checkpoint.path,'utf8')) as any;raw._engine.operationReceipts[identity.operationId].result={reason:'tampered'};await writeFile(checkpoint.path,JSON.stringify(raw),'utf8');await expect(store.restoreCheckpoint('s',checkpoint.id)).rejects.toThrow('检查点 operation receipt 冲突');const state=await store.read('s');expect(state._engine.stateVersion).toBe(1);expect(state.flags).toEqual({kept:true})})
 it('migrates legacy schema v2 states to v3 with an empty receipt map',async()=>{const root=await mkdtemp(join(tmpdir(),'dsh-op-migrate-'));const directory=join(root,'pack','s');await mkdir(directory,{recursive:true});await writeFile(join(directory,'state.json'),JSON.stringify({_engine:{schemaVersion:2,stateVersion:4,packId:'pack',createdAt:'2026-01-01T00:00:00.000Z'},world:{legacy:true}}),'utf8');const store=new SerialStateStore(root,'pack',{});const state=await store.read('s');expect(state._engine.schemaVersion).toBe(3);expect(state._engine.stateVersion).toBe(4);expect(state._engine.operationReceipts).toEqual({});expect(state.world).toEqual({legacy:true})})
 it('rejects unknown future runtime schema versions instead of silently downgrading them',async()=>{const root=await mkdtemp(join(tmpdir(),'dsh-op-future-'));const directory=join(root,'pack','s');await mkdir(directory,{recursive:true});await writeFile(join(directory,'state.json'),JSON.stringify({_engine:{schemaVersion:99,stateVersion:1,packId:'pack',createdAt:'2026-01-01T00:00:00.000Z'}}),'utf8');const store=new SerialStateStore(root,'pack',{});await expect(store.read('s')).rejects.toThrow('不支持的 Runtime Schema 版本')})
})
