import { mkdtemp, mkdir, readFile, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import { discoverAndLoadEpisodes, validateCrossReferences, validateScriptSchema } from './script-loader.js'
import { SerialStateStore } from './serial-state.js'
import type { EpisodeScript } from './serial-types.js'

function episode(id='s1e1', version=1): EpisodeScript { return {
 schemaVersion:1,episodeId:id,season:1,episode:1,title:'开篇',status:'validated',
 continuity:{startsAfter:'',fixedFacts:['既有事实不可倒改'],openThreads:['线索'],seasonDecision:{mode:'continue_current_season',reason:'继续当前冲突'}},
 scenes:[
  {id:'opening',mode:'off_work',title:'开场',entryConditions:[],cast:['主角'],fixedFacts:[],characterGoals:{主角:'调查'},secrets:['幕后真相'],beats:['出现线索'],choices:[{id:'route',prompt:'怎么做？',allowFreeInput:true,options:[{id:'follow',label:'跟踪',consequenceTags:['risk'],nextScene:'ending'},{id:'wait',label:'等待',consequenceTags:['safe'],nextScene:'ending'}]}],dialogueAnchors:[],improvisationEnvelope:['闲聊'],exitConditions:['完成选择'],transitions:[],stateEffects:[]},
  {id:'ending',mode:'off_work',title:'结尾',entryConditions:['完成选择'],cast:['主角'],fixedFacts:[],characterGoals:{},secrets:[],beats:['收束'],choices:[],dialogueAnchors:[],improvisationEnvelope:[],exitConditions:['结束'],transitions:[],stateEffects:[]}
 ],ending:{completionConditions:['ending 完成'],recap:{includeChosen:true,includeDeclined:true,includeConsequences:true,showNetworkPercentages:false,revealHiddenBranches:false}},revision:{version,outOfScriptPolicy:'immediate_pause_revise_validate_resume',history:[{version,reason:'初稿',changedAt:'2026-01-01T00:00:00.000Z'}]}
}}

describe('v0.7 serial scripts',()=>{
 it('validates, indexes and discovers episode JSON files',async()=>{const root=await mkdtemp(join(tmpdir(),'dsh-v07-'));const dir=join(root,'story','episodes');await mkdir(dir,{recursive:true});await writeFile(join(dir,'s1e1.json'),JSON.stringify(episode()),'utf8');const episodes=await discoverAndLoadEpisodes(root);expect(episodes.size).toBe(1);expect(episodes.get('s1e1')?.index.sceneToEpisode.get('opening')).toBe('s1e1');expect(validateCrossReferences(episodes)).toEqual([])})
 it('keeps old packs without an episodes directory compatible',async()=>{const root=await mkdtemp(join(tmpdir(),'dsh-v06-pack-'));expect((await discoverAndLoadEpisodes(root)).size).toBe(0)})
 it('rejects missing transition targets and unreachable scenes',()=>{const value=episode();value.scenes[0].choices[0].options[0].nextScene='missing';const parsed=validateScriptSchema(value);expect(validateCrossReferences(new Map([['s1e1',parsed]])).join(' ')).toContain('不存在场景')})
 it('uses optimistic locking and protects authored truth',async()=>{const root=await mkdtemp(join(tmpdir(),'dsh-state-'));const store=new SerialStateStore(root,'pack',{world:{weather:'rain'}});const first=await store.read('s');expect(first._engine.stateVersion).toBe(0);const next=await store.commit('s',0,{world:{weather:'sun'}},'change');expect(next._engine.stateVersion).toBe(1);await expect(store.commit('s',0,{world:{}},'stale')).rejects.toThrow('版本冲突');await expect(store.commit('s',1,{authoredScript:{}},'forbidden')).rejects.toThrow('保护字段')})
 it('allows only one of two concurrent writes based on the same version',async()=>{const root=await mkdtemp(join(tmpdir(),'dsh-lock-'));const store=new SerialStateStore(root,'pack',{});const results=await Promise.allSettled([store.commit('s',0,{flags:{a:true}},'a'),store.commit('s',0,{flags:{b:true}},'b')]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect(results.filter(r=>r.status==='rejected')).toHaveLength(1)})
 it('records real choices and computes declined options without hidden data',async()=>{const root=await mkdtemp(join(tmpdir(),'dsh-summary-'));const store=new SerialStateStore(root,'pack',{});await store.recordChoice('s',0,episode(),'opening','route',['follow'],undefined,['被发现']);const result=await store.recordEpisodeSummary('s',1,episode(),'ending',['线索公开']);expect(result.summary.chosen[0].selected[0].label).toBe('跟踪');expect(result.summary.declined[0].options).toEqual([{id:'wait',label:'等待'}]);expect(JSON.stringify(result.summary)).not.toContain('幕后真相')})
 it('does not write invalid revisions and resumes only after valid revision',async()=>{const root=await mkdtemp(join(tmpdir(),'dsh-revision-'));const store=new SerialStateStore(root,'pack',{});await store.pauseForRevision('s',0,'越界','去月球','opening');const invalid=episode('s1e1',2);invalid.scenes[0].choices[0].options[0].nextScene='missing';await expect(store.submitRevision('s',1,invalid,'扩写')).rejects.toThrow('校验失败');expect((await store.read('s')).playedCanon.pauseState).toBe('paused-for-revision');const valid=episode('s1e1',2);const state=await store.submitRevision('s',1,valid,'扩写');expect(state.playedCanon.pauseState).toBe('running');expect(await readFile(state.authoredScript.scripts.s1e1.scriptPath,'utf8')).toContain('"version": 2')})
  it('emits lossless-JSON events without undefined-valued keys (DSH tool output contract)',async()=>{const root=await mkdtemp(join(tmpdir(),'dsh-lossless-'));const store=new SerialStateStore(root,'pack',{});const entered=await store.enterEpisodeScene('s',0,episode(),'opening');const recorded=await store.recordChoice('s',1,episode(),'opening','route',['follow'],undefined,['被发现']);const summarized=await store.recordEpisodeSummary('s',2,episode(),'ending',['线索公开']);for(const state of [entered,recorded,summarized.state]){for(const event of state.playedCanon.events){for(const key of Object.keys(event) as Array<keyof typeof event>){expect(event[key]).not.toBeUndefined()};expect(JSON.parse(JSON.stringify(event))).toEqual(event)}}})
})
